#pragma once
// ============================================================
// hls_config.hpp  –  Single source of truth for ALL parameters
// ============================================================
// Every knob that controls the heat2d HLS kernel lives here as
// a #define.  Vitis HLS reads these during synthesis; the same
// header is included by the testbench so both always agree.
//
// To retarget:
//   change HLS_N / HLS_NUM_STEPS / HLS_NUM_PE and recompile.
// ============================================================

// ---- Grid geometry ------------------------------------------
// N = number of interior points per dimension.
// Full grid is (N+2) x (N+2); boundary rows/cols are fixed BCs.
// Paper Fig.1 uses N=30.  For meaningful parallel speedup
// on FPGA, N>=64 is recommended (more work per PE per step).
#define HLS_N             30
#define HLS_GRID_SIZE     (HLS_N + 2)     // N+2 = full grid side

// ---- Time integration ---------------------------------------
// Number of explicit Euler steps per kernel invocation.
// Stability: r = c*dt/ds^2 must be <= 0.5; we fix r=0.25.
#define HLS_NUM_STEPS     10000

// How often the testbench snapshots the grid (every N steps).
// Set to 0 to disable snapshots (faster testbench).
#define HLS_SNAPSHOT_INT  500

// ---- Physics ------------------------------------------------
// c = thermal diffusivity (paper §1 uses 0.1)
#define HLS_C             0.1

// r = c * dt / ds^2  must equal 0.25 for stability.
// With dt = ds^2 / (4c), r = 0.25 exactly.
// We bake the constant 0.25 into the stencil so the synthesiser
// can implement it as a multiply-by-constant (shift+add on fixed
// point, or a DSP-efficient op on doubles).
#define HLS_R             0.25

// ---- Boundary conditions (constant, paper §1 example) -------
#define HLS_BC_LEFT       10.0    // u[0][j]       – x=0 edge
#define HLS_BC_RIGHT      40.0    // u[N+1][j]     – x=1 edge
#define HLS_BC_BOTTOM     30.0    // u[i][0]       – y=0 edge
#define HLS_BC_TOP        50.0    // u[i][N+1]     – y=1 edge

// ---- Initial condition for interior points ------------------
// Set HLS_IC_RANDOM to 1 to use a pseudo-random IC (paper Fig.1).
// IC values are generated by the testbench; the kernel only
// receives the already-initialised grid.
#define HLS_IC_ZERO       0.0
#define HLS_IC_RANDOM     1       // 1 = random IC in testbench

// ---- Parallelism (parallel kernel only) --------------------
// HLS_NUM_PE: number of "processing elements" = unroll factor
// applied to the row (i) loop.
// Equivalent to the number of MPI processors (m) in the paper.
//
// Constraint: HLS_N must be divisible by HLS_NUM_PE for clean
// partitioning (non-divisible N is handled with boundary checks
// inside the loop – same as the paper's ifirst/ilast logic).
//
// On FPGA, each PE runs concurrently, reading its own row bank
// from partitioned BRAM.  No ghost-row communication is needed
// because ALL PEs read from the same shared u_old snapshot –
// this is the key FPGA advantage over MPI.
#define HLS_NUM_PE        4

// ---- Array partition factor for serial kernel ---------------
// Cyclic partitioning of the column dimension allows the pipelined
// j-loop to access u[i][j-1], u[i][j], u[i][j+1] in one cycle.
// Factor of 4 covers the 3 column accesses per stencil with margin.
#define HLS_COL_PART      4

// ---- Interface mode selector --------------------------------
// HLS_IFACE_BRAM  : on-chip BRAM (small grids, N<=128 typical)
// HLS_IFACE_M_AXI : off-chip DDR via AXI4 master (large grids)
// Only one should be defined.
#define HLS_IFACE_BRAM

// ---- Clock / target -----------------------------------------
// Used by run_hls.tcl for synthesis constraints.
// Adjust for your target board.
#define HLS_CLOCK_PERIOD_NS  10    // 100 MHz
// #define HLS_PART           "xcu280-fsvh2892-2L-e"  // Alveo U280
// #define HLS_PART           "xczu9eg-ffvb1156-2-i"  // ZCU102

// ---- Derived constants (do not change) ----------------------
// These reproduce the paper's formulas so the stencil coefficient
// is always exactly 0.25 regardless of N.
// ds = 1/(N+1),  dt = ds^2/(4c),  r = c*dt/ds^2 = 0.25
#define HLS_DS            (1.0 / (HLS_N + 1.0))
#define HLS_DT            ((HLS_DS * HLS_DS) / (4.0 * HLS_C))

// Maximum steps hint for LOOP_TRIPCOUNT pragma
#define HLS_MAX_STEPS_HINT  HLS_NUM_STEPS
