-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity heat2d_serial_hls_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    u_a_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_ce0 : OUT STD_LOGIC;
    u_a_we0 : OUT STD_LOGIC;
    u_a_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_1_ce0 : OUT STD_LOGIC;
    u_a_1_we0 : OUT STD_LOGIC;
    u_a_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_2_ce0 : OUT STD_LOGIC;
    u_a_2_we0 : OUT STD_LOGIC;
    u_a_2_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_3_ce0 : OUT STD_LOGIC;
    u_a_3_we0 : OUT STD_LOGIC;
    u_a_3_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_4_ce0 : OUT STD_LOGIC;
    u_a_4_we0 : OUT STD_LOGIC;
    u_a_4_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_5_ce0 : OUT STD_LOGIC;
    u_a_5_we0 : OUT STD_LOGIC;
    u_a_5_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_6_ce0 : OUT STD_LOGIC;
    u_a_6_we0 : OUT STD_LOGIC;
    u_a_6_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_7_ce0 : OUT STD_LOGIC;
    u_a_7_we0 : OUT STD_LOGIC;
    u_a_7_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_8_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_8_ce0 : OUT STD_LOGIC;
    u_a_8_we0 : OUT STD_LOGIC;
    u_a_8_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_9_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_9_ce0 : OUT STD_LOGIC;
    u_a_9_we0 : OUT STD_LOGIC;
    u_a_9_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_10_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_10_ce0 : OUT STD_LOGIC;
    u_a_10_we0 : OUT STD_LOGIC;
    u_a_10_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_a_11_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    u_a_11_ce0 : OUT STD_LOGIC;
    u_a_11_we0 : OUT STD_LOGIC;
    u_a_11_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_b_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    u_b_ce0 : OUT STD_LOGIC;
    u_b_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    u_b_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    u_b_1_ce0 : OUT STD_LOGIC;
    u_b_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    u_b_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    u_b_2_ce0 : OUT STD_LOGIC;
    u_b_2_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    u_b_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    u_b_3_ce0 : OUT STD_LOGIC;
    u_b_3_q0 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of heat2d_serial_hls_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_384 : STD_LOGIC_VECTOR (9 downto 0) := "1110000100";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv11_2B : STD_LOGIC_VECTOR (10 downto 0) := "00000101011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln115_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln115_1_fu_377_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln115_1_reg_556 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln115_1_reg_556_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln115_1_reg_556_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln115_1_reg_556_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln115_1_reg_556_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln115_1_reg_556_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln115_1_reg_556_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln116_fu_391_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln116_reg_563 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln116_reg_563_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln116_reg_563_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln116_reg_563_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln116_reg_563_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln116_reg_563_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln116_reg_563_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln116_reg_563_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln2_reg_568 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln2_reg_568_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln2_reg_568_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln2_reg_568_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln2_reg_568_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln2_reg_568_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln2_reg_568_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln2_reg_568_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_35_cast_reg_574 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln118_1_fu_461_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln118_fu_480_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_94 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln116_fu_415_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (4 downto 0);
    signal i_fu_98 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten6_fu_102 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln115_1_fu_345_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (9 downto 0);
    signal u_b_ce0_local : STD_LOGIC;
    signal u_b_1_ce0_local : STD_LOGIC;
    signal u_b_2_ce0_local : STD_LOGIC;
    signal u_b_3_ce0_local : STD_LOGIC;
    signal u_a_7_we0_local : STD_LOGIC;
    signal trunc_ln115_fu_469_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_496_p11 : STD_LOGIC_VECTOR (63 downto 0);
    signal u_a_7_ce0_local : STD_LOGIC;
    signal u_a_6_we0_local : STD_LOGIC;
    signal u_a_6_ce0_local : STD_LOGIC;
    signal u_a_8_we0_local : STD_LOGIC;
    signal u_a_8_ce0_local : STD_LOGIC;
    signal u_a_4_we0_local : STD_LOGIC;
    signal u_a_4_ce0_local : STD_LOGIC;
    signal u_a_3_we0_local : STD_LOGIC;
    signal u_a_3_ce0_local : STD_LOGIC;
    signal u_a_5_we0_local : STD_LOGIC;
    signal u_a_5_ce0_local : STD_LOGIC;
    signal u_a_1_we0_local : STD_LOGIC;
    signal u_a_1_ce0_local : STD_LOGIC;
    signal u_a_we0_local : STD_LOGIC;
    signal u_a_ce0_local : STD_LOGIC;
    signal u_a_2_we0_local : STD_LOGIC;
    signal u_a_2_ce0_local : STD_LOGIC;
    signal u_a_10_we0_local : STD_LOGIC;
    signal u_a_10_ce0_local : STD_LOGIC;
    signal u_a_9_we0_local : STD_LOGIC;
    signal u_a_9_ce0_local : STD_LOGIC;
    signal u_a_11_we0_local : STD_LOGIC;
    signal u_a_11_ce0_local : STD_LOGIC;
    signal icmp_ln116_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln115_fu_357_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_385_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_385_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln115_fu_369_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln115_fu_439_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln115_fu_439_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln115_fu_439_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_455_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_385_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_474_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_2_fu_496_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln115_fu_439_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_496_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_496_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_496_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_496_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component heat2d_serial_hls_urem_5ns_3ns_2_9_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component heat2d_serial_hls_mul_5ns_7ns_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component heat2d_serial_hls_sparsemux_9_2_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        din2 : IN STD_LOGIC_VECTOR (63 downto 0);
        din3 : IN STD_LOGIC_VECTOR (63 downto 0);
        def : IN STD_LOGIC_VECTOR (63 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component heat2d_serial_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_5ns_3ns_2_9_1_U76 : component heat2d_serial_hls_urem_5ns_3ns_2_9_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 5,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_385_p0,
        din1 => grp_fu_385_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_385_p2);

    mul_5ns_7ns_11_1_1_U77 : component heat2d_serial_hls_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln115_fu_439_p0,
        din1 => mul_ln115_fu_439_p1,
        dout => mul_ln115_fu_439_p2);

    sparsemux_9_2_64_1_1_U78 : component heat2d_serial_hls_sparsemux_9_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "10",
        din2_WIDTH => 64,
        CASE3 => "11",
        din3_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => u_b_q0,
        din1 => u_b_1_q0,
        din2 => u_b_2_q0,
        din3 => u_b_3_q0,
        def => tmp_2_fu_496_p9,
        sel => trunc_ln116_reg_563_pp0_iter7_reg,
        dout => tmp_2_fu_496_p11);

    flow_control_loop_pipe_sequential_init_U : component heat2d_serial_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    i_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln115_fu_339_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_98 <= select_ln115_1_fu_377_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_98 <= ap_const_lv5_1;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten6_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln115_fu_339_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_102 <= add_ln115_1_fu_345_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_102 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln115_fu_339_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_94 <= add_ln116_fu_415_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_94 <= ap_const_lv5_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                lshr_ln2_reg_568 <= select_ln115_fu_369_p3(4 downto 2);
                lshr_ln2_reg_568_pp0_iter1_reg <= lshr_ln2_reg_568;
                select_ln115_1_reg_556 <= select_ln115_1_fu_377_p3;
                select_ln115_1_reg_556_pp0_iter1_reg <= select_ln115_1_reg_556;
                trunc_ln116_reg_563 <= trunc_ln116_fu_391_p1;
                trunc_ln116_reg_563_pp0_iter1_reg <= trunc_ln116_reg_563;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                lshr_ln2_reg_568_pp0_iter2_reg <= lshr_ln2_reg_568_pp0_iter1_reg;
                lshr_ln2_reg_568_pp0_iter3_reg <= lshr_ln2_reg_568_pp0_iter2_reg;
                lshr_ln2_reg_568_pp0_iter4_reg <= lshr_ln2_reg_568_pp0_iter3_reg;
                lshr_ln2_reg_568_pp0_iter5_reg <= lshr_ln2_reg_568_pp0_iter4_reg;
                lshr_ln2_reg_568_pp0_iter6_reg <= lshr_ln2_reg_568_pp0_iter5_reg;
                lshr_ln2_reg_568_pp0_iter7_reg <= lshr_ln2_reg_568_pp0_iter6_reg;
                select_ln115_1_reg_556_pp0_iter2_reg <= select_ln115_1_reg_556_pp0_iter1_reg;
                select_ln115_1_reg_556_pp0_iter3_reg <= select_ln115_1_reg_556_pp0_iter2_reg;
                select_ln115_1_reg_556_pp0_iter4_reg <= select_ln115_1_reg_556_pp0_iter3_reg;
                select_ln115_1_reg_556_pp0_iter5_reg <= select_ln115_1_reg_556_pp0_iter4_reg;
                select_ln115_1_reg_556_pp0_iter6_reg <= select_ln115_1_reg_556_pp0_iter5_reg;
                tmp_35_cast_reg_574 <= mul_ln115_fu_439_p2(10 downto 7);
                trunc_ln116_reg_563_pp0_iter2_reg <= trunc_ln116_reg_563_pp0_iter1_reg;
                trunc_ln116_reg_563_pp0_iter3_reg <= trunc_ln116_reg_563_pp0_iter2_reg;
                trunc_ln116_reg_563_pp0_iter4_reg <= trunc_ln116_reg_563_pp0_iter3_reg;
                trunc_ln116_reg_563_pp0_iter5_reg <= trunc_ln116_reg_563_pp0_iter4_reg;
                trunc_ln116_reg_563_pp0_iter6_reg <= trunc_ln116_reg_563_pp0_iter5_reg;
                trunc_ln116_reg_563_pp0_iter7_reg <= trunc_ln116_reg_563_pp0_iter6_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln115_1_fu_345_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv10_1));
    add_ln115_fu_357_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv5_1));
    add_ln116_fu_415_p2 <= std_logic_vector(unsigned(select_ln115_fu_369_p3) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln115_fu_339_p2)
    begin
        if (((icmp_ln115_fu_339_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_98)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv5_1;
        else 
            ap_sig_allocacmp_i_load <= i_fu_98;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_102)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_102;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_94, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv5_1;
        else 
            ap_sig_allocacmp_j_load <= j_fu_94;
        end if; 
    end process;

    grp_fu_385_p0 <= 
        add_ln115_fu_357_p2 when (icmp_ln116_fu_363_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    grp_fu_385_p1 <= ap_const_lv5_3(3 - 1 downto 0);
    icmp_ln115_fu_339_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv10_384) else "0";
    icmp_ln116_fu_363_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv5_1F) else "0";
    mul_ln115_fu_439_p0 <= mul_ln115_fu_439_p00(5 - 1 downto 0);
    mul_ln115_fu_439_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln115_1_reg_556_pp0_iter6_reg),11));
    mul_ln115_fu_439_p1 <= ap_const_lv11_2B(7 - 1 downto 0);
    select_ln115_1_fu_377_p3 <= 
        add_ln115_fu_357_p2 when (icmp_ln116_fu_363_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln115_fu_369_p3 <= 
        ap_const_lv5_1 when (icmp_ln116_fu_363_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
    tmp_1_fu_455_p3 <= (select_ln115_1_reg_556_pp0_iter6_reg & lshr_ln2_reg_568_pp0_iter6_reg);
    tmp_2_fu_496_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_s_fu_474_p3 <= (tmp_35_cast_reg_574 & lshr_ln2_reg_568_pp0_iter7_reg);
    trunc_ln115_fu_469_p1 <= grp_fu_385_p2(2 - 1 downto 0);
    trunc_ln116_fu_391_p1 <= select_ln115_fu_369_p3(2 - 1 downto 0);
    u_a_10_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_10_ce0 <= u_a_10_ce0_local;

    u_a_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_10_ce0_local <= ap_const_logic_1;
        else 
            u_a_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_10_d0 <= tmp_2_fu_496_p11;
    u_a_10_we0 <= u_a_10_we0_local;

    u_a_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln115_fu_469_p1 = ap_const_lv2_1) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_3))) then 
            u_a_10_we0_local <= ap_const_logic_1;
        else 
            u_a_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_11_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_11_ce0 <= u_a_11_ce0_local;

    u_a_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_11_ce0_local <= ap_const_logic_1;
        else 
            u_a_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_11_d0 <= tmp_2_fu_496_p11;
    u_a_11_we0 <= u_a_11_we0_local;

    u_a_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if ((not((trunc_ln115_fu_469_p1 = ap_const_lv2_0)) and not((trunc_ln115_fu_469_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_3))) then 
            u_a_11_we0_local <= ap_const_logic_1;
        else 
            u_a_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_1_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_1_ce0 <= u_a_1_ce0_local;

    u_a_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_1_ce0_local <= ap_const_logic_1;
        else 
            u_a_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_1_d0 <= tmp_2_fu_496_p11;
    u_a_1_we0 <= u_a_1_we0_local;

    u_a_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln115_fu_469_p1 = ap_const_lv2_1) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_0))) then 
            u_a_1_we0_local <= ap_const_logic_1;
        else 
            u_a_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_2_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_2_ce0 <= u_a_2_ce0_local;

    u_a_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_2_ce0_local <= ap_const_logic_1;
        else 
            u_a_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_2_d0 <= tmp_2_fu_496_p11;
    u_a_2_we0 <= u_a_2_we0_local;

    u_a_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if ((not((trunc_ln115_fu_469_p1 = ap_const_lv2_0)) and not((trunc_ln115_fu_469_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_0))) then 
            u_a_2_we0_local <= ap_const_logic_1;
        else 
            u_a_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_3_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_3_ce0 <= u_a_3_ce0_local;

    u_a_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_3_ce0_local <= ap_const_logic_1;
        else 
            u_a_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_3_d0 <= tmp_2_fu_496_p11;
    u_a_3_we0 <= u_a_3_we0_local;

    u_a_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln115_fu_469_p1 = ap_const_lv2_0) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_1))) then 
            u_a_3_we0_local <= ap_const_logic_1;
        else 
            u_a_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_4_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_4_ce0 <= u_a_4_ce0_local;

    u_a_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_4_ce0_local <= ap_const_logic_1;
        else 
            u_a_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_4_d0 <= tmp_2_fu_496_p11;
    u_a_4_we0 <= u_a_4_we0_local;

    u_a_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln115_fu_469_p1 = ap_const_lv2_1) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_1))) then 
            u_a_4_we0_local <= ap_const_logic_1;
        else 
            u_a_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_5_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_5_ce0 <= u_a_5_ce0_local;

    u_a_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_5_ce0_local <= ap_const_logic_1;
        else 
            u_a_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_5_d0 <= tmp_2_fu_496_p11;
    u_a_5_we0 <= u_a_5_we0_local;

    u_a_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if ((not((trunc_ln115_fu_469_p1 = ap_const_lv2_0)) and not((trunc_ln115_fu_469_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_1))) then 
            u_a_5_we0_local <= ap_const_logic_1;
        else 
            u_a_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_6_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_6_ce0 <= u_a_6_ce0_local;

    u_a_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_6_ce0_local <= ap_const_logic_1;
        else 
            u_a_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_6_d0 <= tmp_2_fu_496_p11;
    u_a_6_we0 <= u_a_6_we0_local;

    u_a_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln115_fu_469_p1 = ap_const_lv2_0) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_2))) then 
            u_a_6_we0_local <= ap_const_logic_1;
        else 
            u_a_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_7_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_7_ce0 <= u_a_7_ce0_local;

    u_a_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_7_ce0_local <= ap_const_logic_1;
        else 
            u_a_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_7_d0 <= tmp_2_fu_496_p11;
    u_a_7_we0 <= u_a_7_we0_local;

    u_a_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln115_fu_469_p1 = ap_const_lv2_1) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_2))) then 
            u_a_7_we0_local <= ap_const_logic_1;
        else 
            u_a_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_8_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_8_ce0 <= u_a_8_ce0_local;

    u_a_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_8_ce0_local <= ap_const_logic_1;
        else 
            u_a_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_8_d0 <= tmp_2_fu_496_p11;
    u_a_8_we0 <= u_a_8_we0_local;

    u_a_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if ((not((trunc_ln115_fu_469_p1 = ap_const_lv2_0)) and not((trunc_ln115_fu_469_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_2))) then 
            u_a_8_we0_local <= ap_const_logic_1;
        else 
            u_a_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_9_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_9_ce0 <= u_a_9_ce0_local;

    u_a_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_9_ce0_local <= ap_const_logic_1;
        else 
            u_a_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_9_d0 <= tmp_2_fu_496_p11;
    u_a_9_we0 <= u_a_9_we0_local;

    u_a_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln115_fu_469_p1 = ap_const_lv2_0) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_3))) then 
            u_a_9_we0_local <= ap_const_logic_1;
        else 
            u_a_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_address0 <= zext_ln118_fu_480_p1(7 - 1 downto 0);
    u_a_ce0 <= u_a_ce0_local;

    u_a_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            u_a_ce0_local <= ap_const_logic_1;
        else 
            u_a_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_a_d0 <= tmp_2_fu_496_p11;
    u_a_we0 <= u_a_we0_local;

    u_a_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln116_reg_563_pp0_iter7_reg, trunc_ln115_fu_469_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln115_fu_469_p1 = ap_const_lv2_0) and (trunc_ln116_reg_563_pp0_iter7_reg = ap_const_lv2_0))) then 
            u_a_we0_local <= ap_const_logic_1;
        else 
            u_a_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_b_1_address0 <= zext_ln118_1_fu_461_p1(8 - 1 downto 0);
    u_b_1_ce0 <= u_b_1_ce0_local;

    u_b_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            u_b_1_ce0_local <= ap_const_logic_1;
        else 
            u_b_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_b_2_address0 <= zext_ln118_1_fu_461_p1(8 - 1 downto 0);
    u_b_2_ce0 <= u_b_2_ce0_local;

    u_b_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            u_b_2_ce0_local <= ap_const_logic_1;
        else 
            u_b_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_b_3_address0 <= zext_ln118_1_fu_461_p1(8 - 1 downto 0);
    u_b_3_ce0 <= u_b_3_ce0_local;

    u_b_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            u_b_3_ce0_local <= ap_const_logic_1;
        else 
            u_b_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_b_address0 <= zext_ln118_1_fu_461_p1(8 - 1 downto 0);
    u_b_ce0 <= u_b_ce0_local;

    u_b_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            u_b_ce0_local <= ap_const_logic_1;
        else 
            u_b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln118_1_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_455_p3),64));
    zext_ln118_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_474_p3),64));
end behav;
