// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module heat2d_serial_hls_heat2d_serial_hls_Pipeline_STENCIL_J (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul_ln92,
        u_a_address0,
        u_a_ce0,
        u_a_q0,
        mul_ln104,
        mul_ln93,
        u_a_1_address0,
        u_a_1_ce0,
        u_a_1_q0,
        u_a_2_address0,
        u_a_2_ce0,
        u_a_2_q0,
        u_a_3_address0,
        u_a_3_ce0,
        u_a_3_q0,
        u_a_4_address0,
        u_a_4_ce0,
        u_a_4_q0,
        u_a_5_address0,
        u_a_5_ce0,
        u_a_5_q0,
        u_a_6_address0,
        u_a_6_ce0,
        u_a_6_q0,
        u_a_7_address0,
        u_a_7_ce0,
        u_a_7_q0,
        u_a_8_address0,
        u_a_8_ce0,
        u_a_8_q0,
        u_a_9_address0,
        u_a_9_ce0,
        u_a_9_q0,
        u_a_10_address0,
        u_a_10_ce0,
        u_a_10_q0,
        u_a_11_address0,
        u_a_11_ce0,
        u_a_11_q0,
        i_1,
        u_b_address0,
        u_b_ce0,
        u_b_we0,
        u_b_d0,
        u_b_1_address0,
        u_b_1_ce0,
        u_b_1_we0,
        u_b_1_d0,
        u_b_2_address0,
        u_b_2_ce0,
        u_b_2_we0,
        u_b_2_d0,
        u_b_3_address0,
        u_b_3_ce0,
        u_b_3_we0,
        u_b_3_d0,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [10:0] mul_ln92;
output  [6:0] u_a_address0;
output   u_a_ce0;
input  [63:0] u_a_q0;
input  [10:0] mul_ln104;
input  [10:0] mul_ln93;
output  [6:0] u_a_1_address0;
output   u_a_1_ce0;
input  [63:0] u_a_1_q0;
output  [6:0] u_a_2_address0;
output   u_a_2_ce0;
input  [63:0] u_a_2_q0;
output  [6:0] u_a_3_address0;
output   u_a_3_ce0;
input  [63:0] u_a_3_q0;
output  [6:0] u_a_4_address0;
output   u_a_4_ce0;
input  [63:0] u_a_4_q0;
output  [6:0] u_a_5_address0;
output   u_a_5_ce0;
input  [63:0] u_a_5_q0;
output  [6:0] u_a_6_address0;
output   u_a_6_ce0;
input  [63:0] u_a_6_q0;
output  [6:0] u_a_7_address0;
output   u_a_7_ce0;
input  [63:0] u_a_7_q0;
output  [6:0] u_a_8_address0;
output   u_a_8_ce0;
input  [63:0] u_a_8_q0;
output  [6:0] u_a_9_address0;
output   u_a_9_ce0;
input  [63:0] u_a_9_q0;
output  [6:0] u_a_10_address0;
output   u_a_10_ce0;
input  [63:0] u_a_10_q0;
output  [6:0] u_a_11_address0;
output   u_a_11_ce0;
input  [63:0] u_a_11_q0;
input  [4:0] i_1;
output  [7:0] u_b_address0;
output   u_b_ce0;
output   u_b_we0;
output  [63:0] u_b_d0;
output  [7:0] u_b_1_address0;
output   u_b_1_ce0;
output   u_b_1_we0;
output  [63:0] u_b_1_d0;
output  [7:0] u_b_2_address0;
output   u_b_2_ce0;
output   u_b_2_we0;
output  [63:0] u_b_2_d0;
output  [7:0] u_b_3_address0;
output   u_b_3_ce0;
output   u_b_3_we0;
output  [63:0] u_b_3_d0;
input  [1:0] empty;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln93_fu_850_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] tmp_19_reg_1349;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] j_1_reg_1385;
wire   [1:0] trunc_ln93_fu_856_p1;
reg   [1:0] trunc_ln93_reg_1395;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter1_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter2_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter3_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter4_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter5_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter6_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter7_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter8_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter9_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter10_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter11_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter12_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter13_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter14_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter15_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter16_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter17_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter18_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter19_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter20_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter21_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter22_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter23_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter24_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter25_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter26_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter27_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter28_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter29_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter30_reg;
reg   [1:0] trunc_ln93_reg_1395_pp0_iter31_reg;
reg   [2:0] lshr_ln5_reg_1404;
wire   [2:0] lshr_ln3_fu_891_p4;
reg   [2:0] lshr_ln3_reg_1409;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter2_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter3_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter4_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter5_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter6_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter7_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter8_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter9_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter10_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter11_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter12_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter13_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter14_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter15_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter16_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter17_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter18_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter19_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter20_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter21_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter22_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter23_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter24_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter25_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter26_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter27_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter28_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter29_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter30_reg;
reg   [2:0] lshr_ln3_reg_1409_pp0_iter31_reg;
wire   [63:0] center_assign_fu_1061_p11;
reg   [63:0] center_assign_reg_1714;
reg   [63:0] center_assign_reg_1714_pp0_iter3_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter4_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter5_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter6_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter7_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter8_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter9_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter10_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter11_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter12_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter13_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter14_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter15_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter16_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter17_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter18_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter19_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter20_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter21_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter22_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter23_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter24_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter25_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter26_reg;
reg   [63:0] center_assign_reg_1714_pp0_iter27_reg;
wire   [63:0] north_assign_fu_1160_p11;
reg   [63:0] north_assign_reg_1720;
wire   [63:0] south_assign_fu_1259_p11;
reg   [63:0] south_assign_reg_1725;
wire   [63:0] west_assign_fu_1282_p11;
reg   [63:0] west_assign_reg_1730;
reg   [63:0] west_assign_reg_1730_pp0_iter3_reg;
reg   [63:0] west_assign_reg_1730_pp0_iter4_reg;
reg   [63:0] west_assign_reg_1730_pp0_iter5_reg;
reg   [63:0] west_assign_reg_1730_pp0_iter6_reg;
reg   [63:0] west_assign_reg_1730_pp0_iter7_reg;
reg   [63:0] west_assign_reg_1730_pp0_iter8_reg;
reg   [63:0] west_assign_reg_1730_pp0_iter9_reg;
reg   [63:0] west_assign_reg_1730_pp0_iter10_reg;
reg   [63:0] west_assign_reg_1730_pp0_iter11_reg;
reg   [63:0] west_assign_reg_1730_pp0_iter12_reg;
wire   [63:0] east_assign_fu_1305_p11;
reg   [63:0] east_assign_reg_1735;
reg   [63:0] east_assign_reg_1735_pp0_iter3_reg;
reg   [63:0] east_assign_reg_1735_pp0_iter4_reg;
reg   [63:0] east_assign_reg_1735_pp0_iter5_reg;
reg   [63:0] east_assign_reg_1735_pp0_iter6_reg;
reg   [63:0] east_assign_reg_1735_pp0_iter7_reg;
wire   [63:0] grp_fu_732_p2;
reg   [63:0] add_i_reg_1740;
wire   [63:0] grp_fu_736_p2;
reg   [63:0] add1_i_reg_1745;
wire   [63:0] grp_fu_740_p2;
reg   [63:0] add2_i_reg_1750;
wire   [63:0] grp_fu_756_p2;
reg   [63:0] mul_i_reg_1755;
wire   [63:0] grp_fu_744_p2;
reg   [63:0] sub_i_reg_1760;
wire   [63:0] grp_fu_761_p2;
reg   [63:0] mul3_i_reg_1765;
wire   [63:0] zext_ln102_fu_917_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln103_fu_950_p1;
wire   [63:0] zext_ln104_fu_983_p1;
wire   [63:0] zext_ln105_fu_1022_p1;
wire   [63:0] zext_ln106_fu_1045_p1;
wire   [63:0] zext_ln101_fu_1334_p1;
reg   [4:0] j_fu_106;
wire   [4:0] add_ln106_fu_860_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j_1;
reg    u_a_ce0_local;
reg   [6:0] u_a_address0_local;
reg    u_a_1_ce0_local;
reg   [6:0] u_a_1_address0_local;
reg    u_a_2_ce0_local;
reg   [6:0] u_a_2_address0_local;
reg    u_a_3_ce0_local;
reg   [6:0] u_a_3_address0_local;
reg    u_a_4_ce0_local;
reg   [6:0] u_a_4_address0_local;
reg    u_a_5_ce0_local;
reg   [6:0] u_a_5_address0_local;
reg    u_a_6_ce0_local;
reg   [6:0] u_a_6_address0_local;
reg    u_a_7_ce0_local;
reg   [6:0] u_a_7_address0_local;
reg    u_a_8_ce0_local;
reg   [6:0] u_a_8_address0_local;
reg    u_a_9_ce0_local;
reg   [6:0] u_a_9_address0_local;
reg    u_a_10_ce0_local;
reg   [6:0] u_a_10_address0_local;
reg    u_a_11_ce0_local;
reg   [6:0] u_a_11_address0_local;
reg    u_b_2_we0_local;
wire   [63:0] grp_fu_748_p2;
reg    u_b_2_ce0_local;
reg    u_b_1_we0_local;
reg    u_b_1_ce0_local;
reg    u_b_we0_local;
reg    u_b_ce0_local;
reg    u_b_3_we0_local;
reg    u_b_3_ce0_local;
wire   [63:0] grp_fu_766_p7;
wire   [63:0] grp_fu_785_p7;
wire   [63:0] grp_fu_804_p7;
wire   [63:0] grp_fu_823_p7;
wire   [3:0] p_cast_fu_900_p4;
wire   [6:0] tmp_20_fu_909_p3;
wire   [3:0] p_cast1_fu_933_p4;
wire   [6:0] tmp_21_fu_942_p3;
wire   [3:0] p_cast2_fu_966_p4;
wire   [6:0] tmp_22_fu_975_p3;
wire   [4:0] add_ln105_fu_999_p2;
wire   [2:0] lshr_ln4_fu_1004_p4;
wire   [6:0] tmp_24_fu_1014_p3;
wire   [6:0] tmp_25_fu_1038_p3;
wire   [63:0] grp_fu_766_p9;
wire   [63:0] grp_fu_785_p9;
wire   [63:0] grp_fu_804_p9;
wire   [63:0] grp_fu_823_p9;
wire   [63:0] center_assign_fu_1061_p9;
wire   [63:0] tmp_5_fu_1084_p7;
wire   [63:0] tmp_6_fu_1103_p7;
wire   [63:0] tmp_7_fu_1122_p7;
wire   [63:0] tmp_8_fu_1141_p7;
wire   [63:0] tmp_5_fu_1084_p9;
wire   [63:0] tmp_6_fu_1103_p9;
wire   [63:0] tmp_7_fu_1122_p9;
wire   [63:0] tmp_8_fu_1141_p9;
wire   [63:0] north_assign_fu_1160_p9;
wire   [63:0] tmp_s_fu_1183_p7;
wire   [63:0] tmp_4_fu_1202_p7;
wire   [63:0] tmp_9_fu_1221_p7;
wire   [63:0] tmp_10_fu_1240_p7;
wire   [63:0] tmp_s_fu_1183_p9;
wire   [63:0] tmp_4_fu_1202_p9;
wire   [63:0] tmp_9_fu_1221_p9;
wire   [63:0] tmp_10_fu_1240_p9;
wire   [63:0] south_assign_fu_1259_p9;
wire   [63:0] west_assign_fu_1282_p9;
wire   [63:0] east_assign_fu_1305_p9;
wire   [7:0] tmp_23_fu_1328_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_636;
wire   [1:0] grp_fu_766_p1;
wire   [1:0] grp_fu_766_p3;
wire  signed [1:0] grp_fu_766_p5;
wire   [1:0] grp_fu_785_p1;
wire   [1:0] grp_fu_785_p3;
wire  signed [1:0] grp_fu_785_p5;
wire   [1:0] grp_fu_804_p1;
wire   [1:0] grp_fu_804_p3;
wire  signed [1:0] grp_fu_804_p5;
wire   [1:0] grp_fu_823_p1;
wire   [1:0] grp_fu_823_p3;
wire  signed [1:0] grp_fu_823_p5;
wire   [1:0] center_assign_fu_1061_p1;
wire   [1:0] center_assign_fu_1061_p3;
wire  signed [1:0] center_assign_fu_1061_p5;
wire  signed [1:0] center_assign_fu_1061_p7;
wire   [1:0] tmp_5_fu_1084_p1;
wire  signed [1:0] tmp_5_fu_1084_p3;
wire   [1:0] tmp_5_fu_1084_p5;
wire   [1:0] tmp_6_fu_1103_p1;
wire  signed [1:0] tmp_6_fu_1103_p3;
wire   [1:0] tmp_6_fu_1103_p5;
wire   [1:0] tmp_7_fu_1122_p1;
wire  signed [1:0] tmp_7_fu_1122_p3;
wire   [1:0] tmp_7_fu_1122_p5;
wire   [1:0] tmp_8_fu_1141_p1;
wire  signed [1:0] tmp_8_fu_1141_p3;
wire   [1:0] tmp_8_fu_1141_p5;
wire   [1:0] north_assign_fu_1160_p1;
wire   [1:0] north_assign_fu_1160_p3;
wire  signed [1:0] north_assign_fu_1160_p5;
wire  signed [1:0] north_assign_fu_1160_p7;
wire  signed [1:0] tmp_s_fu_1183_p1;
wire   [1:0] tmp_s_fu_1183_p3;
wire   [1:0] tmp_s_fu_1183_p5;
wire  signed [1:0] tmp_4_fu_1202_p1;
wire   [1:0] tmp_4_fu_1202_p3;
wire   [1:0] tmp_4_fu_1202_p5;
wire  signed [1:0] tmp_9_fu_1221_p1;
wire   [1:0] tmp_9_fu_1221_p3;
wire   [1:0] tmp_9_fu_1221_p5;
wire  signed [1:0] tmp_10_fu_1240_p1;
wire   [1:0] tmp_10_fu_1240_p3;
wire   [1:0] tmp_10_fu_1240_p5;
wire   [1:0] south_assign_fu_1259_p1;
wire   [1:0] south_assign_fu_1259_p3;
wire  signed [1:0] south_assign_fu_1259_p5;
wire  signed [1:0] south_assign_fu_1259_p7;
wire   [1:0] west_assign_fu_1282_p1;
wire  signed [1:0] west_assign_fu_1282_p3;
wire  signed [1:0] west_assign_fu_1282_p5;
wire   [1:0] west_assign_fu_1282_p7;
wire  signed [1:0] east_assign_fu_1305_p1;
wire   [1:0] east_assign_fu_1305_p3;
wire   [1:0] east_assign_fu_1305_p5;
wire  signed [1:0] east_assign_fu_1305_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 j_fu_106 = 5'd0;
#0 ap_done_reg = 1'b0;
end

heat2d_serial_hls_dadd_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(north_assign_reg_1720),
    .din1(south_assign_reg_1725),
    .ce(1'b1),
    .dout(grp_fu_732_p2)
);

heat2d_serial_hls_dadd_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_i_reg_1740),
    .din1(east_assign_reg_1735_pp0_iter7_reg),
    .ce(1'b1),
    .dout(grp_fu_736_p2)
);

heat2d_serial_hls_dadd_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add1_i_reg_1745),
    .din1(west_assign_reg_1730_pp0_iter12_reg),
    .ce(1'b1),
    .dout(grp_fu_740_p2)
);

heat2d_serial_hls_dsub_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsub_64ns_64ns_64_5_full_dsp_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add2_i_reg_1750),
    .din1(mul_i_reg_1755),
    .ce(1'b1),
    .dout(grp_fu_744_p2)
);

heat2d_serial_hls_dadd_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(center_assign_reg_1714_pp0_iter27_reg),
    .din1(mul3_i_reg_1765),
    .ce(1'b1),
    .dout(grp_fu_748_p2)
);

heat2d_serial_hls_dmul_64ns_64ns_64_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(center_assign_reg_1714_pp0_iter12_reg),
    .din1(64'd4616189618054758400),
    .ce(1'b1),
    .dout(grp_fu_756_p2)
);

heat2d_serial_hls_dmul_64ns_64ns_64_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_i_reg_1760),
    .din1(64'd4598175219545276416),
    .ce(1'b1),
    .dout(grp_fu_761_p2)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U29(
    .din0(u_a_q0),
    .din1(u_a_1_q0),
    .din2(u_a_2_q0),
    .def(grp_fu_766_p7),
    .sel(empty),
    .dout(grp_fu_766_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U30(
    .din0(u_a_3_q0),
    .din1(u_a_4_q0),
    .din2(u_a_5_q0),
    .def(grp_fu_785_p7),
    .sel(empty),
    .dout(grp_fu_785_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U31(
    .din0(u_a_6_q0),
    .din1(u_a_7_q0),
    .din2(u_a_8_q0),
    .def(grp_fu_804_p7),
    .sel(empty),
    .dout(grp_fu_804_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U32(
    .din0(u_a_9_q0),
    .din1(u_a_10_q0),
    .din2(u_a_11_q0),
    .def(grp_fu_823_p7),
    .sel(empty),
    .dout(grp_fu_823_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U33(
    .din0(grp_fu_766_p9),
    .din1(grp_fu_785_p9),
    .din2(grp_fu_804_p9),
    .din3(grp_fu_823_p9),
    .def(center_assign_fu_1061_p9),
    .sel(trunc_ln93_reg_1395_pp0_iter1_reg),
    .dout(center_assign_fu_1061_p11)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U34(
    .din0(u_a_q0),
    .din1(u_a_1_q0),
    .din2(u_a_2_q0),
    .def(tmp_5_fu_1084_p7),
    .sel(empty),
    .dout(tmp_5_fu_1084_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U35(
    .din0(u_a_3_q0),
    .din1(u_a_4_q0),
    .din2(u_a_5_q0),
    .def(tmp_6_fu_1103_p7),
    .sel(empty),
    .dout(tmp_6_fu_1103_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U36(
    .din0(u_a_6_q0),
    .din1(u_a_7_q0),
    .din2(u_a_8_q0),
    .def(tmp_7_fu_1122_p7),
    .sel(empty),
    .dout(tmp_7_fu_1122_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U37(
    .din0(u_a_9_q0),
    .din1(u_a_10_q0),
    .din2(u_a_11_q0),
    .def(tmp_8_fu_1141_p7),
    .sel(empty),
    .dout(tmp_8_fu_1141_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U38(
    .din0(tmp_5_fu_1084_p9),
    .din1(tmp_6_fu_1103_p9),
    .din2(tmp_7_fu_1122_p9),
    .din3(tmp_8_fu_1141_p9),
    .def(north_assign_fu_1160_p9),
    .sel(trunc_ln93_reg_1395_pp0_iter1_reg),
    .dout(north_assign_fu_1160_p11)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U39(
    .din0(u_a_q0),
    .din1(u_a_1_q0),
    .din2(u_a_2_q0),
    .def(tmp_s_fu_1183_p7),
    .sel(empty),
    .dout(tmp_s_fu_1183_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U40(
    .din0(u_a_3_q0),
    .din1(u_a_4_q0),
    .din2(u_a_5_q0),
    .def(tmp_4_fu_1202_p7),
    .sel(empty),
    .dout(tmp_4_fu_1202_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U41(
    .din0(u_a_6_q0),
    .din1(u_a_7_q0),
    .din2(u_a_8_q0),
    .def(tmp_9_fu_1221_p7),
    .sel(empty),
    .dout(tmp_9_fu_1221_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U42(
    .din0(u_a_9_q0),
    .din1(u_a_10_q0),
    .din2(u_a_11_q0),
    .def(tmp_10_fu_1240_p7),
    .sel(empty),
    .dout(tmp_10_fu_1240_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U43(
    .din0(tmp_s_fu_1183_p9),
    .din1(tmp_4_fu_1202_p9),
    .din2(tmp_9_fu_1221_p9),
    .din3(tmp_10_fu_1240_p9),
    .def(south_assign_fu_1259_p9),
    .sel(trunc_ln93_reg_1395_pp0_iter1_reg),
    .dout(south_assign_fu_1259_p11)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h0 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U44(
    .din0(grp_fu_766_p9),
    .din1(grp_fu_785_p9),
    .din2(grp_fu_804_p9),
    .din3(grp_fu_823_p9),
    .def(west_assign_fu_1282_p9),
    .sel(trunc_ln93_reg_1395_pp0_iter1_reg),
    .dout(west_assign_fu_1282_p11)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h3 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h2 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U45(
    .din0(grp_fu_766_p9),
    .din1(grp_fu_785_p9),
    .din2(grp_fu_804_p9),
    .din3(grp_fu_823_p9),
    .def(east_assign_fu_1305_p9),
    .sel(trunc_ln93_reg_1395_pp0_iter1_reg),
    .dout(east_assign_fu_1305_p11)
);

heat2d_serial_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter31_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln93_fu_850_p2 == 1'd0))) begin
            j_fu_106 <= add_ln106_fu_860_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_106 <= 5'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add1_i_reg_1745 <= grp_fu_736_p2;
        add2_i_reg_1750 <= grp_fu_740_p2;
        add_i_reg_1740 <= grp_fu_732_p2;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        center_assign_reg_1714 <= center_assign_fu_1061_p11;
        center_assign_reg_1714_pp0_iter10_reg <= center_assign_reg_1714_pp0_iter9_reg;
        center_assign_reg_1714_pp0_iter11_reg <= center_assign_reg_1714_pp0_iter10_reg;
        center_assign_reg_1714_pp0_iter12_reg <= center_assign_reg_1714_pp0_iter11_reg;
        center_assign_reg_1714_pp0_iter13_reg <= center_assign_reg_1714_pp0_iter12_reg;
        center_assign_reg_1714_pp0_iter14_reg <= center_assign_reg_1714_pp0_iter13_reg;
        center_assign_reg_1714_pp0_iter15_reg <= center_assign_reg_1714_pp0_iter14_reg;
        center_assign_reg_1714_pp0_iter16_reg <= center_assign_reg_1714_pp0_iter15_reg;
        center_assign_reg_1714_pp0_iter17_reg <= center_assign_reg_1714_pp0_iter16_reg;
        center_assign_reg_1714_pp0_iter18_reg <= center_assign_reg_1714_pp0_iter17_reg;
        center_assign_reg_1714_pp0_iter19_reg <= center_assign_reg_1714_pp0_iter18_reg;
        center_assign_reg_1714_pp0_iter20_reg <= center_assign_reg_1714_pp0_iter19_reg;
        center_assign_reg_1714_pp0_iter21_reg <= center_assign_reg_1714_pp0_iter20_reg;
        center_assign_reg_1714_pp0_iter22_reg <= center_assign_reg_1714_pp0_iter21_reg;
        center_assign_reg_1714_pp0_iter23_reg <= center_assign_reg_1714_pp0_iter22_reg;
        center_assign_reg_1714_pp0_iter24_reg <= center_assign_reg_1714_pp0_iter23_reg;
        center_assign_reg_1714_pp0_iter25_reg <= center_assign_reg_1714_pp0_iter24_reg;
        center_assign_reg_1714_pp0_iter26_reg <= center_assign_reg_1714_pp0_iter25_reg;
        center_assign_reg_1714_pp0_iter27_reg <= center_assign_reg_1714_pp0_iter26_reg;
        center_assign_reg_1714_pp0_iter3_reg <= center_assign_reg_1714;
        center_assign_reg_1714_pp0_iter4_reg <= center_assign_reg_1714_pp0_iter3_reg;
        center_assign_reg_1714_pp0_iter5_reg <= center_assign_reg_1714_pp0_iter4_reg;
        center_assign_reg_1714_pp0_iter6_reg <= center_assign_reg_1714_pp0_iter5_reg;
        center_assign_reg_1714_pp0_iter7_reg <= center_assign_reg_1714_pp0_iter6_reg;
        center_assign_reg_1714_pp0_iter8_reg <= center_assign_reg_1714_pp0_iter7_reg;
        center_assign_reg_1714_pp0_iter9_reg <= center_assign_reg_1714_pp0_iter8_reg;
        east_assign_reg_1735 <= east_assign_fu_1305_p11;
        east_assign_reg_1735_pp0_iter3_reg <= east_assign_reg_1735;
        east_assign_reg_1735_pp0_iter4_reg <= east_assign_reg_1735_pp0_iter3_reg;
        east_assign_reg_1735_pp0_iter5_reg <= east_assign_reg_1735_pp0_iter4_reg;
        east_assign_reg_1735_pp0_iter6_reg <= east_assign_reg_1735_pp0_iter5_reg;
        east_assign_reg_1735_pp0_iter7_reg <= east_assign_reg_1735_pp0_iter6_reg;
        lshr_ln3_reg_1409_pp0_iter10_reg <= lshr_ln3_reg_1409_pp0_iter9_reg;
        lshr_ln3_reg_1409_pp0_iter11_reg <= lshr_ln3_reg_1409_pp0_iter10_reg;
        lshr_ln3_reg_1409_pp0_iter12_reg <= lshr_ln3_reg_1409_pp0_iter11_reg;
        lshr_ln3_reg_1409_pp0_iter13_reg <= lshr_ln3_reg_1409_pp0_iter12_reg;
        lshr_ln3_reg_1409_pp0_iter14_reg <= lshr_ln3_reg_1409_pp0_iter13_reg;
        lshr_ln3_reg_1409_pp0_iter15_reg <= lshr_ln3_reg_1409_pp0_iter14_reg;
        lshr_ln3_reg_1409_pp0_iter16_reg <= lshr_ln3_reg_1409_pp0_iter15_reg;
        lshr_ln3_reg_1409_pp0_iter17_reg <= lshr_ln3_reg_1409_pp0_iter16_reg;
        lshr_ln3_reg_1409_pp0_iter18_reg <= lshr_ln3_reg_1409_pp0_iter17_reg;
        lshr_ln3_reg_1409_pp0_iter19_reg <= lshr_ln3_reg_1409_pp0_iter18_reg;
        lshr_ln3_reg_1409_pp0_iter20_reg <= lshr_ln3_reg_1409_pp0_iter19_reg;
        lshr_ln3_reg_1409_pp0_iter21_reg <= lshr_ln3_reg_1409_pp0_iter20_reg;
        lshr_ln3_reg_1409_pp0_iter22_reg <= lshr_ln3_reg_1409_pp0_iter21_reg;
        lshr_ln3_reg_1409_pp0_iter23_reg <= lshr_ln3_reg_1409_pp0_iter22_reg;
        lshr_ln3_reg_1409_pp0_iter24_reg <= lshr_ln3_reg_1409_pp0_iter23_reg;
        lshr_ln3_reg_1409_pp0_iter25_reg <= lshr_ln3_reg_1409_pp0_iter24_reg;
        lshr_ln3_reg_1409_pp0_iter26_reg <= lshr_ln3_reg_1409_pp0_iter25_reg;
        lshr_ln3_reg_1409_pp0_iter27_reg <= lshr_ln3_reg_1409_pp0_iter26_reg;
        lshr_ln3_reg_1409_pp0_iter28_reg <= lshr_ln3_reg_1409_pp0_iter27_reg;
        lshr_ln3_reg_1409_pp0_iter29_reg <= lshr_ln3_reg_1409_pp0_iter28_reg;
        lshr_ln3_reg_1409_pp0_iter2_reg <= lshr_ln3_reg_1409;
        lshr_ln3_reg_1409_pp0_iter30_reg <= lshr_ln3_reg_1409_pp0_iter29_reg;
        lshr_ln3_reg_1409_pp0_iter31_reg <= lshr_ln3_reg_1409_pp0_iter30_reg;
        lshr_ln3_reg_1409_pp0_iter3_reg <= lshr_ln3_reg_1409_pp0_iter2_reg;
        lshr_ln3_reg_1409_pp0_iter4_reg <= lshr_ln3_reg_1409_pp0_iter3_reg;
        lshr_ln3_reg_1409_pp0_iter5_reg <= lshr_ln3_reg_1409_pp0_iter4_reg;
        lshr_ln3_reg_1409_pp0_iter6_reg <= lshr_ln3_reg_1409_pp0_iter5_reg;
        lshr_ln3_reg_1409_pp0_iter7_reg <= lshr_ln3_reg_1409_pp0_iter6_reg;
        lshr_ln3_reg_1409_pp0_iter8_reg <= lshr_ln3_reg_1409_pp0_iter7_reg;
        lshr_ln3_reg_1409_pp0_iter9_reg <= lshr_ln3_reg_1409_pp0_iter8_reg;
        mul3_i_reg_1765 <= grp_fu_761_p2;
        mul_i_reg_1755 <= grp_fu_756_p2;
        north_assign_reg_1720 <= north_assign_fu_1160_p11;
        south_assign_reg_1725 <= south_assign_fu_1259_p11;
        sub_i_reg_1760 <= grp_fu_744_p2;
        trunc_ln93_reg_1395_pp0_iter10_reg <= trunc_ln93_reg_1395_pp0_iter9_reg;
        trunc_ln93_reg_1395_pp0_iter11_reg <= trunc_ln93_reg_1395_pp0_iter10_reg;
        trunc_ln93_reg_1395_pp0_iter12_reg <= trunc_ln93_reg_1395_pp0_iter11_reg;
        trunc_ln93_reg_1395_pp0_iter13_reg <= trunc_ln93_reg_1395_pp0_iter12_reg;
        trunc_ln93_reg_1395_pp0_iter14_reg <= trunc_ln93_reg_1395_pp0_iter13_reg;
        trunc_ln93_reg_1395_pp0_iter15_reg <= trunc_ln93_reg_1395_pp0_iter14_reg;
        trunc_ln93_reg_1395_pp0_iter16_reg <= trunc_ln93_reg_1395_pp0_iter15_reg;
        trunc_ln93_reg_1395_pp0_iter17_reg <= trunc_ln93_reg_1395_pp0_iter16_reg;
        trunc_ln93_reg_1395_pp0_iter18_reg <= trunc_ln93_reg_1395_pp0_iter17_reg;
        trunc_ln93_reg_1395_pp0_iter19_reg <= trunc_ln93_reg_1395_pp0_iter18_reg;
        trunc_ln93_reg_1395_pp0_iter20_reg <= trunc_ln93_reg_1395_pp0_iter19_reg;
        trunc_ln93_reg_1395_pp0_iter21_reg <= trunc_ln93_reg_1395_pp0_iter20_reg;
        trunc_ln93_reg_1395_pp0_iter22_reg <= trunc_ln93_reg_1395_pp0_iter21_reg;
        trunc_ln93_reg_1395_pp0_iter23_reg <= trunc_ln93_reg_1395_pp0_iter22_reg;
        trunc_ln93_reg_1395_pp0_iter24_reg <= trunc_ln93_reg_1395_pp0_iter23_reg;
        trunc_ln93_reg_1395_pp0_iter25_reg <= trunc_ln93_reg_1395_pp0_iter24_reg;
        trunc_ln93_reg_1395_pp0_iter26_reg <= trunc_ln93_reg_1395_pp0_iter25_reg;
        trunc_ln93_reg_1395_pp0_iter27_reg <= trunc_ln93_reg_1395_pp0_iter26_reg;
        trunc_ln93_reg_1395_pp0_iter28_reg <= trunc_ln93_reg_1395_pp0_iter27_reg;
        trunc_ln93_reg_1395_pp0_iter29_reg <= trunc_ln93_reg_1395_pp0_iter28_reg;
        trunc_ln93_reg_1395_pp0_iter2_reg <= trunc_ln93_reg_1395_pp0_iter1_reg;
        trunc_ln93_reg_1395_pp0_iter30_reg <= trunc_ln93_reg_1395_pp0_iter29_reg;
        trunc_ln93_reg_1395_pp0_iter31_reg <= trunc_ln93_reg_1395_pp0_iter30_reg;
        trunc_ln93_reg_1395_pp0_iter3_reg <= trunc_ln93_reg_1395_pp0_iter2_reg;
        trunc_ln93_reg_1395_pp0_iter4_reg <= trunc_ln93_reg_1395_pp0_iter3_reg;
        trunc_ln93_reg_1395_pp0_iter5_reg <= trunc_ln93_reg_1395_pp0_iter4_reg;
        trunc_ln93_reg_1395_pp0_iter6_reg <= trunc_ln93_reg_1395_pp0_iter5_reg;
        trunc_ln93_reg_1395_pp0_iter7_reg <= trunc_ln93_reg_1395_pp0_iter6_reg;
        trunc_ln93_reg_1395_pp0_iter8_reg <= trunc_ln93_reg_1395_pp0_iter7_reg;
        trunc_ln93_reg_1395_pp0_iter9_reg <= trunc_ln93_reg_1395_pp0_iter8_reg;
        west_assign_reg_1730 <= west_assign_fu_1282_p11;
        west_assign_reg_1730_pp0_iter10_reg <= west_assign_reg_1730_pp0_iter9_reg;
        west_assign_reg_1730_pp0_iter11_reg <= west_assign_reg_1730_pp0_iter10_reg;
        west_assign_reg_1730_pp0_iter12_reg <= west_assign_reg_1730_pp0_iter11_reg;
        west_assign_reg_1730_pp0_iter3_reg <= west_assign_reg_1730;
        west_assign_reg_1730_pp0_iter4_reg <= west_assign_reg_1730_pp0_iter3_reg;
        west_assign_reg_1730_pp0_iter5_reg <= west_assign_reg_1730_pp0_iter4_reg;
        west_assign_reg_1730_pp0_iter6_reg <= west_assign_reg_1730_pp0_iter5_reg;
        west_assign_reg_1730_pp0_iter7_reg <= west_assign_reg_1730_pp0_iter6_reg;
        west_assign_reg_1730_pp0_iter8_reg <= west_assign_reg_1730_pp0_iter7_reg;
        west_assign_reg_1730_pp0_iter9_reg <= west_assign_reg_1730_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        j_1_reg_1385 <= ap_sig_allocacmp_j_1;
        lshr_ln3_reg_1409 <= {{j_1_reg_1385[4:2]}};
        lshr_ln5_reg_1404 <= {{add_ln106_fu_860_p2[4:2]}};
        trunc_ln93_reg_1395 <= trunc_ln93_fu_856_p1;
        trunc_ln93_reg_1395_pp0_iter1_reg <= trunc_ln93_reg_1395;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln93_fu_850_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter31_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) 
    & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 5'd1;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_106;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_10_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_10_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_10_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_10_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_10_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_10_address0_local = 'bx;
        end
    end else begin
        u_a_10_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_10_ce0_local = 1'b1;
    end else begin
        u_a_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_11_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_11_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_11_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_11_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_11_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_11_address0_local = 'bx;
        end
    end else begin
        u_a_11_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_11_ce0_local = 1'b1;
    end else begin
        u_a_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_1_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_1_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_1_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_1_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_1_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_1_address0_local = 'bx;
        end
    end else begin
        u_a_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_1_ce0_local = 1'b1;
    end else begin
        u_a_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_2_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_2_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_2_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_2_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_2_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_2_address0_local = 'bx;
        end
    end else begin
        u_a_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_2_ce0_local = 1'b1;
    end else begin
        u_a_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_3_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_3_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_3_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_3_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_3_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_3_address0_local = 'bx;
        end
    end else begin
        u_a_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_3_ce0_local = 1'b1;
    end else begin
        u_a_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_4_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_4_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_4_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_4_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_4_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_4_address0_local = 'bx;
        end
    end else begin
        u_a_4_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_4_ce0_local = 1'b1;
    end else begin
        u_a_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_5_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_5_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_5_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_5_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_5_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_5_address0_local = 'bx;
        end
    end else begin
        u_a_5_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_5_ce0_local = 1'b1;
    end else begin
        u_a_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_6_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_6_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_6_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_6_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_6_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_6_address0_local = 'bx;
        end
    end else begin
        u_a_6_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_6_ce0_local = 1'b1;
    end else begin
        u_a_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_7_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_7_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_7_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_7_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_7_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_7_address0_local = 'bx;
        end
    end else begin
        u_a_7_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_7_ce0_local = 1'b1;
    end else begin
        u_a_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_8_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_8_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_8_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_8_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_8_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_8_address0_local = 'bx;
        end
    end else begin
        u_a_8_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_8_ce0_local = 1'b1;
    end else begin
        u_a_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_9_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_9_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_9_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_9_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_9_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_9_address0_local = 'bx;
        end
    end else begin
        u_a_9_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd2) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_9_ce0_local = 1'b1;
    end else begin
        u_a_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_636)) begin
        if (((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_address0_local = zext_ln106_fu_1045_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_address0_local = zext_ln105_fu_1022_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd2))) begin
            u_a_address0_local = zext_ln104_fu_983_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd1))) begin
            u_a_address0_local = zext_ln103_fu_950_p1;
        end else if (((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd0))) begin
            u_a_address0_local = zext_ln102_fu_917_p1;
        end else begin
            u_a_address0_local = 'bx;
        end
    end else begin
        u_a_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln93_reg_1395 == 2'd3) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd1) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((trunc_ln93_reg_1395 == 2'd0) & (tmp_19_reg_1349 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        u_a_ce0_local = 1'b1;
    end else begin
        u_a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter32 == 1'b1))) begin
        u_b_1_ce0_local = 1'b1;
    end else begin
        u_b_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln93_reg_1395_pp0_iter31_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter32 == 1'b1))) begin
        u_b_1_we0_local = 1'b1;
    end else begin
        u_b_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter32 == 1'b1))) begin
        u_b_2_ce0_local = 1'b1;
    end else begin
        u_b_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln93_reg_1395_pp0_iter31_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter32 == 1'b1))) begin
        u_b_2_we0_local = 1'b1;
    end else begin
        u_b_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter32 == 1'b1))) begin
        u_b_3_ce0_local = 1'b1;
    end else begin
        u_b_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln93_reg_1395_pp0_iter31_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter32 == 1'b1))) begin
        u_b_3_we0_local = 1'b1;
    end else begin
        u_b_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter32 == 1'b1))) begin
        u_b_ce0_local = 1'b1;
    end else begin
        u_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln93_reg_1395_pp0_iter31_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter32 == 1'b1))) begin
        u_b_we0_local = 1'b1;
    end else begin
        u_b_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln105_fu_999_p2 = ($signed(j_1_reg_1385) + $signed(5'd31));

assign add_ln106_fu_860_p2 = (ap_sig_allocacmp_j_1 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_636 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign center_assign_fu_1061_p9 = 'bx;

assign east_assign_fu_1305_p9 = 'bx;

assign grp_fu_766_p7 = 'bx;

assign grp_fu_785_p7 = 'bx;

assign grp_fu_804_p7 = 'bx;

assign grp_fu_823_p7 = 'bx;

assign icmp_ln93_fu_850_p2 = ((ap_sig_allocacmp_j_1 == 5'd31) ? 1'b1 : 1'b0);

assign lshr_ln3_fu_891_p4 = {{j_1_reg_1385[4:2]}};

assign lshr_ln4_fu_1004_p4 = {{add_ln105_fu_999_p2[4:2]}};

assign north_assign_fu_1160_p9 = 'bx;

assign p_cast1_fu_933_p4 = {{mul_ln104[10:7]}};

assign p_cast2_fu_966_p4 = {{mul_ln93[10:7]}};

assign p_cast_fu_900_p4 = {{mul_ln92[10:7]}};

assign south_assign_fu_1259_p9 = 'bx;

assign tmp_10_fu_1240_p7 = 'bx;

assign tmp_19_reg_1349 = empty;

assign tmp_20_fu_909_p3 = {{p_cast_fu_900_p4}, {lshr_ln3_fu_891_p4}};

assign tmp_21_fu_942_p3 = {{p_cast1_fu_933_p4}, {lshr_ln3_fu_891_p4}};

assign tmp_22_fu_975_p3 = {{p_cast2_fu_966_p4}, {lshr_ln3_fu_891_p4}};

assign tmp_23_fu_1328_p3 = {{i_1}, {lshr_ln3_reg_1409_pp0_iter31_reg}};

assign tmp_24_fu_1014_p3 = {{p_cast_fu_900_p4}, {lshr_ln4_fu_1004_p4}};

assign tmp_25_fu_1038_p3 = {{p_cast_fu_900_p4}, {lshr_ln5_reg_1404}};

assign tmp_4_fu_1202_p7 = 'bx;

assign tmp_5_fu_1084_p7 = 'bx;

assign tmp_6_fu_1103_p7 = 'bx;

assign tmp_7_fu_1122_p7 = 'bx;

assign tmp_8_fu_1141_p7 = 'bx;

assign tmp_9_fu_1221_p7 = 'bx;

assign tmp_s_fu_1183_p7 = 'bx;

assign trunc_ln93_fu_856_p1 = ap_sig_allocacmp_j_1[1:0];

assign u_a_10_address0 = u_a_10_address0_local;

assign u_a_10_ce0 = u_a_10_ce0_local;

assign u_a_11_address0 = u_a_11_address0_local;

assign u_a_11_ce0 = u_a_11_ce0_local;

assign u_a_1_address0 = u_a_1_address0_local;

assign u_a_1_ce0 = u_a_1_ce0_local;

assign u_a_2_address0 = u_a_2_address0_local;

assign u_a_2_ce0 = u_a_2_ce0_local;

assign u_a_3_address0 = u_a_3_address0_local;

assign u_a_3_ce0 = u_a_3_ce0_local;

assign u_a_4_address0 = u_a_4_address0_local;

assign u_a_4_ce0 = u_a_4_ce0_local;

assign u_a_5_address0 = u_a_5_address0_local;

assign u_a_5_ce0 = u_a_5_ce0_local;

assign u_a_6_address0 = u_a_6_address0_local;

assign u_a_6_ce0 = u_a_6_ce0_local;

assign u_a_7_address0 = u_a_7_address0_local;

assign u_a_7_ce0 = u_a_7_ce0_local;

assign u_a_8_address0 = u_a_8_address0_local;

assign u_a_8_ce0 = u_a_8_ce0_local;

assign u_a_9_address0 = u_a_9_address0_local;

assign u_a_9_ce0 = u_a_9_ce0_local;

assign u_a_address0 = u_a_address0_local;

assign u_a_ce0 = u_a_ce0_local;

assign u_b_1_address0 = zext_ln101_fu_1334_p1;

assign u_b_1_ce0 = u_b_1_ce0_local;

assign u_b_1_d0 = grp_fu_748_p2;

assign u_b_1_we0 = u_b_1_we0_local;

assign u_b_2_address0 = zext_ln101_fu_1334_p1;

assign u_b_2_ce0 = u_b_2_ce0_local;

assign u_b_2_d0 = grp_fu_748_p2;

assign u_b_2_we0 = u_b_2_we0_local;

assign u_b_3_address0 = zext_ln101_fu_1334_p1;

assign u_b_3_ce0 = u_b_3_ce0_local;

assign u_b_3_d0 = grp_fu_748_p2;

assign u_b_3_we0 = u_b_3_we0_local;

assign u_b_address0 = zext_ln101_fu_1334_p1;

assign u_b_ce0 = u_b_ce0_local;

assign u_b_d0 = grp_fu_748_p2;

assign u_b_we0 = u_b_we0_local;

assign west_assign_fu_1282_p9 = 'bx;

assign zext_ln101_fu_1334_p1 = tmp_23_fu_1328_p3;

assign zext_ln102_fu_917_p1 = tmp_20_fu_909_p3;

assign zext_ln103_fu_950_p1 = tmp_21_fu_942_p3;

assign zext_ln104_fu_983_p1 = tmp_22_fu_975_p3;

assign zext_ln105_fu_1022_p1 = tmp_24_fu_1014_p3;

assign zext_ln106_fu_1045_p1 = tmp_25_fu_1038_p3;

endmodule //heat2d_serial_hls_heat2d_serial_hls_Pipeline_STENCIL_J
