// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module heat2d_serial_hls_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        u_a_address0,
        u_a_ce0,
        u_a_we0,
        u_a_d0,
        u_a_1_address0,
        u_a_1_ce0,
        u_a_1_we0,
        u_a_1_d0,
        u_a_2_address0,
        u_a_2_ce0,
        u_a_2_we0,
        u_a_2_d0,
        u_a_3_address0,
        u_a_3_ce0,
        u_a_3_we0,
        u_a_3_d0,
        u_a_4_address0,
        u_a_4_ce0,
        u_a_4_we0,
        u_a_4_d0,
        u_a_5_address0,
        u_a_5_ce0,
        u_a_5_we0,
        u_a_5_d0,
        u_a_6_address0,
        u_a_6_ce0,
        u_a_6_we0,
        u_a_6_d0,
        u_a_7_address0,
        u_a_7_ce0,
        u_a_7_we0,
        u_a_7_d0,
        u_a_8_address0,
        u_a_8_ce0,
        u_a_8_we0,
        u_a_8_d0,
        u_a_9_address0,
        u_a_9_ce0,
        u_a_9_we0,
        u_a_9_d0,
        u_a_10_address0,
        u_a_10_ce0,
        u_a_10_we0,
        u_a_10_d0,
        u_a_11_address0,
        u_a_11_ce0,
        u_a_11_we0,
        u_a_11_d0,
        u_b_address0,
        u_b_ce0,
        u_b_q0,
        u_b_1_address0,
        u_b_1_ce0,
        u_b_1_q0,
        u_b_2_address0,
        u_b_2_ce0,
        u_b_2_q0,
        u_b_3_address0,
        u_b_3_ce0,
        u_b_3_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] u_a_address0;
output   u_a_ce0;
output   u_a_we0;
output  [63:0] u_a_d0;
output  [6:0] u_a_1_address0;
output   u_a_1_ce0;
output   u_a_1_we0;
output  [63:0] u_a_1_d0;
output  [6:0] u_a_2_address0;
output   u_a_2_ce0;
output   u_a_2_we0;
output  [63:0] u_a_2_d0;
output  [6:0] u_a_3_address0;
output   u_a_3_ce0;
output   u_a_3_we0;
output  [63:0] u_a_3_d0;
output  [6:0] u_a_4_address0;
output   u_a_4_ce0;
output   u_a_4_we0;
output  [63:0] u_a_4_d0;
output  [6:0] u_a_5_address0;
output   u_a_5_ce0;
output   u_a_5_we0;
output  [63:0] u_a_5_d0;
output  [6:0] u_a_6_address0;
output   u_a_6_ce0;
output   u_a_6_we0;
output  [63:0] u_a_6_d0;
output  [6:0] u_a_7_address0;
output   u_a_7_ce0;
output   u_a_7_we0;
output  [63:0] u_a_7_d0;
output  [6:0] u_a_8_address0;
output   u_a_8_ce0;
output   u_a_8_we0;
output  [63:0] u_a_8_d0;
output  [6:0] u_a_9_address0;
output   u_a_9_ce0;
output   u_a_9_we0;
output  [63:0] u_a_9_d0;
output  [6:0] u_a_10_address0;
output   u_a_10_ce0;
output   u_a_10_we0;
output  [63:0] u_a_10_d0;
output  [6:0] u_a_11_address0;
output   u_a_11_ce0;
output   u_a_11_we0;
output  [63:0] u_a_11_d0;
output  [7:0] u_b_address0;
output   u_b_ce0;
input  [63:0] u_b_q0;
output  [7:0] u_b_1_address0;
output   u_b_1_ce0;
input  [63:0] u_b_1_q0;
output  [7:0] u_b_2_address0;
output   u_b_2_ce0;
input  [63:0] u_b_2_q0;
output  [7:0] u_b_3_address0;
output   u_b_3_ce0;
input  [63:0] u_b_3_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln115_fu_339_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln115_1_fu_377_p3;
reg   [4:0] select_ln115_1_reg_556;
reg   [4:0] select_ln115_1_reg_556_pp0_iter1_reg;
reg   [4:0] select_ln115_1_reg_556_pp0_iter2_reg;
reg   [4:0] select_ln115_1_reg_556_pp0_iter3_reg;
reg   [4:0] select_ln115_1_reg_556_pp0_iter4_reg;
reg   [4:0] select_ln115_1_reg_556_pp0_iter5_reg;
reg   [4:0] select_ln115_1_reg_556_pp0_iter6_reg;
wire   [1:0] trunc_ln116_fu_391_p1;
reg   [1:0] trunc_ln116_reg_563;
reg   [1:0] trunc_ln116_reg_563_pp0_iter1_reg;
reg   [1:0] trunc_ln116_reg_563_pp0_iter2_reg;
reg   [1:0] trunc_ln116_reg_563_pp0_iter3_reg;
reg   [1:0] trunc_ln116_reg_563_pp0_iter4_reg;
reg   [1:0] trunc_ln116_reg_563_pp0_iter5_reg;
reg   [1:0] trunc_ln116_reg_563_pp0_iter6_reg;
reg   [1:0] trunc_ln116_reg_563_pp0_iter7_reg;
reg   [2:0] lshr_ln2_reg_568;
reg   [2:0] lshr_ln2_reg_568_pp0_iter1_reg;
reg   [2:0] lshr_ln2_reg_568_pp0_iter2_reg;
reg   [2:0] lshr_ln2_reg_568_pp0_iter3_reg;
reg   [2:0] lshr_ln2_reg_568_pp0_iter4_reg;
reg   [2:0] lshr_ln2_reg_568_pp0_iter5_reg;
reg   [2:0] lshr_ln2_reg_568_pp0_iter6_reg;
reg   [2:0] lshr_ln2_reg_568_pp0_iter7_reg;
reg   [3:0] tmp_35_cast_reg_574;
wire   [63:0] zext_ln118_1_fu_461_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln118_fu_480_p1;
reg   [4:0] j_fu_94;
wire   [4:0] add_ln116_fu_415_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j_load;
reg   [4:0] i_fu_98;
reg   [4:0] ap_sig_allocacmp_i_load;
reg   [9:0] indvar_flatten6_fu_102;
wire   [9:0] add_ln115_1_fu_345_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    u_b_ce0_local;
reg    u_b_1_ce0_local;
reg    u_b_2_ce0_local;
reg    u_b_3_ce0_local;
reg    u_a_7_we0_local;
wire   [1:0] trunc_ln115_fu_469_p1;
wire   [63:0] tmp_2_fu_496_p11;
reg    u_a_7_ce0_local;
reg    u_a_6_we0_local;
reg    u_a_6_ce0_local;
reg    u_a_8_we0_local;
reg    u_a_8_ce0_local;
reg    u_a_4_we0_local;
reg    u_a_4_ce0_local;
reg    u_a_3_we0_local;
reg    u_a_3_ce0_local;
reg    u_a_5_we0_local;
reg    u_a_5_ce0_local;
reg    u_a_1_we0_local;
reg    u_a_1_ce0_local;
reg    u_a_we0_local;
reg    u_a_ce0_local;
reg    u_a_2_we0_local;
reg    u_a_2_ce0_local;
reg    u_a_10_we0_local;
reg    u_a_10_ce0_local;
reg    u_a_9_we0_local;
reg    u_a_9_ce0_local;
reg    u_a_11_we0_local;
reg    u_a_11_ce0_local;
wire   [0:0] icmp_ln116_fu_363_p2;
wire   [4:0] add_ln115_fu_357_p2;
wire   [4:0] grp_fu_385_p0;
wire   [2:0] grp_fu_385_p1;
wire   [4:0] select_ln115_fu_369_p3;
wire   [4:0] mul_ln115_fu_439_p0;
wire   [6:0] mul_ln115_fu_439_p1;
wire   [10:0] mul_ln115_fu_439_p2;
wire   [7:0] tmp_1_fu_455_p3;
wire   [1:0] grp_fu_385_p2;
wire   [6:0] tmp_s_fu_474_p3;
wire   [63:0] tmp_2_fu_496_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [10:0] mul_ln115_fu_439_p00;
wire   [1:0] tmp_2_fu_496_p1;
wire   [1:0] tmp_2_fu_496_p3;
wire  signed [1:0] tmp_2_fu_496_p5;
wire  signed [1:0] tmp_2_fu_496_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 j_fu_94 = 5'd0;
#0 i_fu_98 = 5'd0;
#0 indvar_flatten6_fu_102 = 10'd0;
#0 ap_done_reg = 1'b0;
end

heat2d_serial_hls_urem_5ns_3ns_2_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_5ns_3ns_2_9_1_U76(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_385_p0),
    .din1(grp_fu_385_p1),
    .ce(1'b1),
    .dout(grp_fu_385_p2)
);

heat2d_serial_hls_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U77(
    .din0(mul_ln115_fu_439_p0),
    .din1(mul_ln115_fu_439_p1),
    .dout(mul_ln115_fu_439_p2)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U78(
    .din0(u_b_q0),
    .din1(u_b_1_q0),
    .din2(u_b_2_q0),
    .din3(u_b_3_q0),
    .def(tmp_2_fu_496_p9),
    .sel(trunc_ln116_reg_563_pp0_iter7_reg),
    .dout(tmp_2_fu_496_p11)
);

heat2d_serial_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln115_fu_339_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_98 <= select_ln115_1_fu_377_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_98 <= 5'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln115_fu_339_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_102 <= add_ln115_1_fu_345_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_102 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln115_fu_339_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_94 <= add_ln116_fu_415_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_94 <= 5'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        lshr_ln2_reg_568 <= {{select_ln115_fu_369_p3[4:2]}};
        lshr_ln2_reg_568_pp0_iter1_reg <= lshr_ln2_reg_568;
        select_ln115_1_reg_556 <= select_ln115_1_fu_377_p3;
        select_ln115_1_reg_556_pp0_iter1_reg <= select_ln115_1_reg_556;
        trunc_ln116_reg_563 <= trunc_ln116_fu_391_p1;
        trunc_ln116_reg_563_pp0_iter1_reg <= trunc_ln116_reg_563;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        lshr_ln2_reg_568_pp0_iter2_reg <= lshr_ln2_reg_568_pp0_iter1_reg;
        lshr_ln2_reg_568_pp0_iter3_reg <= lshr_ln2_reg_568_pp0_iter2_reg;
        lshr_ln2_reg_568_pp0_iter4_reg <= lshr_ln2_reg_568_pp0_iter3_reg;
        lshr_ln2_reg_568_pp0_iter5_reg <= lshr_ln2_reg_568_pp0_iter4_reg;
        lshr_ln2_reg_568_pp0_iter6_reg <= lshr_ln2_reg_568_pp0_iter5_reg;
        lshr_ln2_reg_568_pp0_iter7_reg <= lshr_ln2_reg_568_pp0_iter6_reg;
        select_ln115_1_reg_556_pp0_iter2_reg <= select_ln115_1_reg_556_pp0_iter1_reg;
        select_ln115_1_reg_556_pp0_iter3_reg <= select_ln115_1_reg_556_pp0_iter2_reg;
        select_ln115_1_reg_556_pp0_iter4_reg <= select_ln115_1_reg_556_pp0_iter3_reg;
        select_ln115_1_reg_556_pp0_iter5_reg <= select_ln115_1_reg_556_pp0_iter4_reg;
        select_ln115_1_reg_556_pp0_iter6_reg <= select_ln115_1_reg_556_pp0_iter5_reg;
        tmp_35_cast_reg_574 <= {{mul_ln115_fu_439_p2[10:7]}};
        trunc_ln116_reg_563_pp0_iter2_reg <= trunc_ln116_reg_563_pp0_iter1_reg;
        trunc_ln116_reg_563_pp0_iter3_reg <= trunc_ln116_reg_563_pp0_iter2_reg;
        trunc_ln116_reg_563_pp0_iter4_reg <= trunc_ln116_reg_563_pp0_iter3_reg;
        trunc_ln116_reg_563_pp0_iter5_reg <= trunc_ln116_reg_563_pp0_iter4_reg;
        trunc_ln116_reg_563_pp0_iter6_reg <= trunc_ln116_reg_563_pp0_iter5_reg;
        trunc_ln116_reg_563_pp0_iter7_reg <= trunc_ln116_reg_563_pp0_iter6_reg;
    end
end

always @ (*) begin
    if (((icmp_ln115_fu_339_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 5'd1;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 5'd1;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_10_ce0_local = 1'b1;
    end else begin
        u_a_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln115_fu_469_p1 == 2'd1) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd3))) begin
        u_a_10_we0_local = 1'b1;
    end else begin
        u_a_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_11_ce0_local = 1'b1;
    end else begin
        u_a_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln115_fu_469_p1 == 2'd0) & ~(trunc_ln115_fu_469_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd3))) begin
        u_a_11_we0_local = 1'b1;
    end else begin
        u_a_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_1_ce0_local = 1'b1;
    end else begin
        u_a_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln115_fu_469_p1 == 2'd1) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd0))) begin
        u_a_1_we0_local = 1'b1;
    end else begin
        u_a_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_2_ce0_local = 1'b1;
    end else begin
        u_a_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln115_fu_469_p1 == 2'd0) & ~(trunc_ln115_fu_469_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd0))) begin
        u_a_2_we0_local = 1'b1;
    end else begin
        u_a_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_3_ce0_local = 1'b1;
    end else begin
        u_a_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln115_fu_469_p1 == 2'd0) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd1))) begin
        u_a_3_we0_local = 1'b1;
    end else begin
        u_a_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_4_ce0_local = 1'b1;
    end else begin
        u_a_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln115_fu_469_p1 == 2'd1) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd1))) begin
        u_a_4_we0_local = 1'b1;
    end else begin
        u_a_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_5_ce0_local = 1'b1;
    end else begin
        u_a_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln115_fu_469_p1 == 2'd0) & ~(trunc_ln115_fu_469_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd1))) begin
        u_a_5_we0_local = 1'b1;
    end else begin
        u_a_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_6_ce0_local = 1'b1;
    end else begin
        u_a_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln115_fu_469_p1 == 2'd0) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd2))) begin
        u_a_6_we0_local = 1'b1;
    end else begin
        u_a_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_7_ce0_local = 1'b1;
    end else begin
        u_a_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln115_fu_469_p1 == 2'd1) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd2))) begin
        u_a_7_we0_local = 1'b1;
    end else begin
        u_a_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_8_ce0_local = 1'b1;
    end else begin
        u_a_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln115_fu_469_p1 == 2'd0) & ~(trunc_ln115_fu_469_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd2))) begin
        u_a_8_we0_local = 1'b1;
    end else begin
        u_a_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_9_ce0_local = 1'b1;
    end else begin
        u_a_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln115_fu_469_p1 == 2'd0) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd3))) begin
        u_a_9_we0_local = 1'b1;
    end else begin
        u_a_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_ce0_local = 1'b1;
    end else begin
        u_a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln115_fu_469_p1 == 2'd0) & (trunc_ln116_reg_563_pp0_iter7_reg == 2'd0))) begin
        u_a_we0_local = 1'b1;
    end else begin
        u_a_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        u_b_1_ce0_local = 1'b1;
    end else begin
        u_b_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        u_b_2_ce0_local = 1'b1;
    end else begin
        u_b_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        u_b_3_ce0_local = 1'b1;
    end else begin
        u_b_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        u_b_ce0_local = 1'b1;
    end else begin
        u_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln115_1_fu_345_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 10'd1);

assign add_ln115_fu_357_p2 = (ap_sig_allocacmp_i_load + 5'd1);

assign add_ln116_fu_415_p2 = (select_ln115_fu_369_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_385_p0 = ((icmp_ln116_fu_363_p2[0:0] == 1'b1) ? add_ln115_fu_357_p2 : ap_sig_allocacmp_i_load);

assign grp_fu_385_p1 = 5'd3;

assign icmp_ln115_fu_339_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 10'd900) ? 1'b1 : 1'b0);

assign icmp_ln116_fu_363_p2 = ((ap_sig_allocacmp_j_load == 5'd31) ? 1'b1 : 1'b0);

assign mul_ln115_fu_439_p0 = mul_ln115_fu_439_p00;

assign mul_ln115_fu_439_p00 = select_ln115_1_reg_556_pp0_iter6_reg;

assign mul_ln115_fu_439_p1 = 11'd43;

assign select_ln115_1_fu_377_p3 = ((icmp_ln116_fu_363_p2[0:0] == 1'b1) ? add_ln115_fu_357_p2 : ap_sig_allocacmp_i_load);

assign select_ln115_fu_369_p3 = ((icmp_ln116_fu_363_p2[0:0] == 1'b1) ? 5'd1 : ap_sig_allocacmp_j_load);

assign tmp_1_fu_455_p3 = {{select_ln115_1_reg_556_pp0_iter6_reg}, {lshr_ln2_reg_568_pp0_iter6_reg}};

assign tmp_2_fu_496_p9 = 'bx;

assign tmp_s_fu_474_p3 = {{tmp_35_cast_reg_574}, {lshr_ln2_reg_568_pp0_iter7_reg}};

assign trunc_ln115_fu_469_p1 = grp_fu_385_p2[1:0];

assign trunc_ln116_fu_391_p1 = select_ln115_fu_369_p3[1:0];

assign u_a_10_address0 = zext_ln118_fu_480_p1;

assign u_a_10_ce0 = u_a_10_ce0_local;

assign u_a_10_d0 = tmp_2_fu_496_p11;

assign u_a_10_we0 = u_a_10_we0_local;

assign u_a_11_address0 = zext_ln118_fu_480_p1;

assign u_a_11_ce0 = u_a_11_ce0_local;

assign u_a_11_d0 = tmp_2_fu_496_p11;

assign u_a_11_we0 = u_a_11_we0_local;

assign u_a_1_address0 = zext_ln118_fu_480_p1;

assign u_a_1_ce0 = u_a_1_ce0_local;

assign u_a_1_d0 = tmp_2_fu_496_p11;

assign u_a_1_we0 = u_a_1_we0_local;

assign u_a_2_address0 = zext_ln118_fu_480_p1;

assign u_a_2_ce0 = u_a_2_ce0_local;

assign u_a_2_d0 = tmp_2_fu_496_p11;

assign u_a_2_we0 = u_a_2_we0_local;

assign u_a_3_address0 = zext_ln118_fu_480_p1;

assign u_a_3_ce0 = u_a_3_ce0_local;

assign u_a_3_d0 = tmp_2_fu_496_p11;

assign u_a_3_we0 = u_a_3_we0_local;

assign u_a_4_address0 = zext_ln118_fu_480_p1;

assign u_a_4_ce0 = u_a_4_ce0_local;

assign u_a_4_d0 = tmp_2_fu_496_p11;

assign u_a_4_we0 = u_a_4_we0_local;

assign u_a_5_address0 = zext_ln118_fu_480_p1;

assign u_a_5_ce0 = u_a_5_ce0_local;

assign u_a_5_d0 = tmp_2_fu_496_p11;

assign u_a_5_we0 = u_a_5_we0_local;

assign u_a_6_address0 = zext_ln118_fu_480_p1;

assign u_a_6_ce0 = u_a_6_ce0_local;

assign u_a_6_d0 = tmp_2_fu_496_p11;

assign u_a_6_we0 = u_a_6_we0_local;

assign u_a_7_address0 = zext_ln118_fu_480_p1;

assign u_a_7_ce0 = u_a_7_ce0_local;

assign u_a_7_d0 = tmp_2_fu_496_p11;

assign u_a_7_we0 = u_a_7_we0_local;

assign u_a_8_address0 = zext_ln118_fu_480_p1;

assign u_a_8_ce0 = u_a_8_ce0_local;

assign u_a_8_d0 = tmp_2_fu_496_p11;

assign u_a_8_we0 = u_a_8_we0_local;

assign u_a_9_address0 = zext_ln118_fu_480_p1;

assign u_a_9_ce0 = u_a_9_ce0_local;

assign u_a_9_d0 = tmp_2_fu_496_p11;

assign u_a_9_we0 = u_a_9_we0_local;

assign u_a_address0 = zext_ln118_fu_480_p1;

assign u_a_ce0 = u_a_ce0_local;

assign u_a_d0 = tmp_2_fu_496_p11;

assign u_a_we0 = u_a_we0_local;

assign u_b_1_address0 = zext_ln118_1_fu_461_p1;

assign u_b_1_ce0 = u_b_1_ce0_local;

assign u_b_2_address0 = zext_ln118_1_fu_461_p1;

assign u_b_2_ce0 = u_b_2_ce0_local;

assign u_b_3_address0 = zext_ln118_1_fu_461_p1;

assign u_b_3_ce0 = u_b_3_ce0_local;

assign u_b_address0 = zext_ln118_1_fu_461_p1;

assign u_b_ce0 = u_b_ce0_local;

assign zext_ln118_1_fu_461_p1 = tmp_1_fu_455_p3;

assign zext_ln118_fu_480_p1 = tmp_s_fu_474_p3;

endmodule //heat2d_serial_hls_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J
