// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="heat2d_serial_hls_heat2d_serial_hls,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu5eg-sfvc784-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.334000,HLS_SYN_LAT=31022071,HLS_SYN_TPT=none,HLS_SYN_MEM=32,HLS_SYN_DSP=0,HLS_SYN_FF=5516,HLS_SYN_LUT=8013,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module heat2d_serial_hls (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        u_in_address0,
        u_in_ce0,
        u_in_q0,
        u_out_address0,
        u_out_ce0,
        u_out_we0,
        u_out_d0,
        s_axi_ctrl_AWVALID,
        s_axi_ctrl_AWREADY,
        s_axi_ctrl_AWADDR,
        s_axi_ctrl_WVALID,
        s_axi_ctrl_WREADY,
        s_axi_ctrl_WDATA,
        s_axi_ctrl_WSTRB,
        s_axi_ctrl_ARVALID,
        s_axi_ctrl_ARREADY,
        s_axi_ctrl_ARADDR,
        s_axi_ctrl_RVALID,
        s_axi_ctrl_RREADY,
        s_axi_ctrl_RDATA,
        s_axi_ctrl_RRESP,
        s_axi_ctrl_BVALID,
        s_axi_ctrl_BREADY,
        s_axi_ctrl_BRESP
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] u_in_address0;
output   u_in_ce0;
input  [63:0] u_in_q0;
output  [9:0] u_out_address0;
output   u_out_ce0;
output   u_out_we0;
output  [63:0] u_out_d0;
input   s_axi_ctrl_AWVALID;
output   s_axi_ctrl_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_AWADDR;
input   s_axi_ctrl_WVALID;
output   s_axi_ctrl_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_ctrl_WSTRB;
input   s_axi_ctrl_ARVALID;
output   s_axi_ctrl_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_ARADDR;
output   s_axi_ctrl_RVALID;
input   s_axi_ctrl_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_RDATA;
output  [1:0] s_axi_ctrl_RRESP;
output   s_axi_ctrl_BVALID;
input   s_axi_ctrl_BREADY;
output  [1:0] s_axi_ctrl_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] num_steps;
reg   [31:0] num_steps_read_reg_352;
wire    ap_CS_fsm_state2;
wire   [30:0] add_ln84_fu_273_p2;
reg   [30:0] add_ln84_reg_360;
wire    ap_CS_fsm_state3;
wire   [10:0] mul_ln92_fu_299_p2;
reg   [10:0] mul_ln92_reg_368;
wire    ap_CS_fsm_state12;
wire   [1:0] trunc_ln92_fu_306_p1;
reg   [1:0] trunc_ln92_reg_373;
wire   [10:0] mul_ln104_fu_321_p2;
reg   [10:0] mul_ln104_reg_378;
wire   [4:0] add_ln104_fu_328_p2;
reg   [4:0] add_ln104_reg_383;
wire   [10:0] mul_ln93_fu_338_p2;
reg   [10:0] mul_ln93_reg_388;
reg   [6:0] u_a_address0;
reg    u_a_ce0;
reg    u_a_we0;
reg   [63:0] u_a_d0;
wire   [63:0] u_a_q0;
reg   [6:0] u_a_1_address0;
reg    u_a_1_ce0;
reg    u_a_1_we0;
reg   [63:0] u_a_1_d0;
wire   [63:0] u_a_1_q0;
reg   [6:0] u_a_2_address0;
reg    u_a_2_ce0;
reg    u_a_2_we0;
reg   [63:0] u_a_2_d0;
wire   [63:0] u_a_2_q0;
reg   [6:0] u_a_3_address0;
reg    u_a_3_ce0;
reg    u_a_3_we0;
reg   [63:0] u_a_3_d0;
wire   [63:0] u_a_3_q0;
reg   [6:0] u_a_4_address0;
reg    u_a_4_ce0;
reg    u_a_4_we0;
reg   [63:0] u_a_4_d0;
wire   [63:0] u_a_4_q0;
reg   [6:0] u_a_5_address0;
reg    u_a_5_ce0;
reg    u_a_5_we0;
reg   [63:0] u_a_5_d0;
wire   [63:0] u_a_5_q0;
reg   [6:0] u_a_6_address0;
reg    u_a_6_ce0;
reg    u_a_6_we0;
reg   [63:0] u_a_6_d0;
wire   [63:0] u_a_6_q0;
reg   [6:0] u_a_7_address0;
reg    u_a_7_ce0;
reg    u_a_7_we0;
reg   [63:0] u_a_7_d0;
wire   [63:0] u_a_7_q0;
reg   [6:0] u_a_8_address0;
reg    u_a_8_ce0;
reg    u_a_8_we0;
reg   [63:0] u_a_8_d0;
wire   [63:0] u_a_8_q0;
reg   [6:0] u_a_9_address0;
reg    u_a_9_ce0;
reg    u_a_9_we0;
reg   [63:0] u_a_9_d0;
wire   [63:0] u_a_9_q0;
reg   [6:0] u_a_10_address0;
reg    u_a_10_ce0;
reg    u_a_10_we0;
reg   [63:0] u_a_10_d0;
wire   [63:0] u_a_10_q0;
reg   [6:0] u_a_11_address0;
reg    u_a_11_ce0;
reg    u_a_11_we0;
reg   [63:0] u_a_11_d0;
wire   [63:0] u_a_11_q0;
reg   [7:0] u_b_address0;
reg    u_b_ce0;
reg    u_b_we0;
reg   [63:0] u_b_d0;
wire   [63:0] u_b_q0;
reg   [7:0] u_b_1_address0;
reg    u_b_1_ce0;
reg    u_b_1_we0;
reg   [63:0] u_b_1_d0;
wire   [63:0] u_b_1_q0;
reg   [7:0] u_b_2_address0;
reg    u_b_2_ce0;
reg    u_b_2_we0;
reg   [63:0] u_b_2_d0;
wire   [63:0] u_b_2_q0;
reg   [7:0] u_b_3_address0;
reg    u_b_3_ce0;
reg    u_b_3_we0;
reg   [63:0] u_b_3_d0;
wire   [63:0] u_b_3_q0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_start;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_done;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_idle;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_ready;
wire   [9:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_in_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_in_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_d0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_d0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_d0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_d0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_address0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_ce0;
wire    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_d0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_start;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_done;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_idle;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_ready;
wire   [9:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_ce0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_1_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_1_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_2_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_2_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_3_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_3_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_4_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_4_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_5_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_5_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_6_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_6_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_7_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_7_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_8_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_8_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_9_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_9_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_10_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_10_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_11_address0;
wire    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_11_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_start;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_done;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_idle;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_ready;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_d0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_ce0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_d0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_ce0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_1_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_1_ce0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_2_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_2_ce0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_3_address0;
wire    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_3_ce0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_start;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_done;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_idle;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_ready;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_1_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_1_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_2_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_2_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_3_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_3_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_4_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_4_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_5_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_5_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_6_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_6_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_7_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_7_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_8_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_8_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_9_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_9_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_10_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_10_ce0;
wire   [6:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_11_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_11_ce0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_ce0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_d0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_ce0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_d0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_ce0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_d0;
wire   [7:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_address0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_ce0;
wire    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_we0;
wire   [63:0] grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_d0;
reg   [4:0] i_reg_142;
wire   [0:0] icmp_ln84_fu_268_p2;
wire    ap_CS_fsm_state13;
reg    grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_start_reg;
reg    grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_start_reg;
wire    ap_CS_fsm_state15;
reg    grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln92_fu_279_p2;
wire    ap_CS_fsm_state14;
reg    grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_start_reg;
reg   [30:0] k_fu_68;
wire   [31:0] zext_ln84_fu_264_p1;
wire   [2:0] grp_fu_285_p1;
wire   [4:0] mul_ln92_fu_299_p0;
wire   [6:0] mul_ln92_fu_299_p1;
wire   [1:0] grp_fu_285_p2;
wire   [4:0] add_ln103_fu_311_p2;
wire   [4:0] mul_ln104_fu_321_p0;
wire   [6:0] mul_ln104_fu_321_p1;
wire   [4:0] mul_ln93_fu_338_p0;
wire   [6:0] mul_ln93_fu_338_p1;
reg    grp_fu_285_ap_start;
wire    grp_fu_285_ap_done;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire   [10:0] mul_ln104_fu_321_p00;
wire   [10:0] mul_ln92_fu_299_p00;
wire   [10:0] mul_ln93_fu_338_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_start_reg = 1'b0;
#0 grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_start_reg = 1'b0;
#0 grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_start_reg = 1'b0;
#0 grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_start_reg = 1'b0;
#0 k_fu_68 = 31'd0;
end

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_address0),
    .ce0(u_a_ce0),
    .we0(u_a_we0),
    .d0(u_a_d0),
    .q0(u_a_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_1_address0),
    .ce0(u_a_1_ce0),
    .we0(u_a_1_we0),
    .d0(u_a_1_d0),
    .q0(u_a_1_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_2_address0),
    .ce0(u_a_2_ce0),
    .we0(u_a_2_we0),
    .d0(u_a_2_d0),
    .q0(u_a_2_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_3_address0),
    .ce0(u_a_3_ce0),
    .we0(u_a_3_we0),
    .d0(u_a_3_d0),
    .q0(u_a_3_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_4_address0),
    .ce0(u_a_4_ce0),
    .we0(u_a_4_we0),
    .d0(u_a_4_d0),
    .q0(u_a_4_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_5_address0),
    .ce0(u_a_5_ce0),
    .we0(u_a_5_we0),
    .d0(u_a_5_d0),
    .q0(u_a_5_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_6_address0),
    .ce0(u_a_6_ce0),
    .we0(u_a_6_we0),
    .d0(u_a_6_d0),
    .q0(u_a_6_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_7_address0),
    .ce0(u_a_7_ce0),
    .we0(u_a_7_we0),
    .d0(u_a_7_d0),
    .q0(u_a_7_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_8_address0),
    .ce0(u_a_8_ce0),
    .we0(u_a_8_we0),
    .d0(u_a_8_d0),
    .q0(u_a_8_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_9_address0),
    .ce0(u_a_9_ce0),
    .we0(u_a_9_we0),
    .d0(u_a_9_d0),
    .q0(u_a_9_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_10_address0),
    .ce0(u_a_10_ce0),
    .we0(u_a_10_we0),
    .d0(u_a_10_d0),
    .q0(u_a_10_q0)
);

heat2d_serial_hls_u_a_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 88 ),
    .AddressWidth( 7 ))
u_a_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_a_11_address0),
    .ce0(u_a_11_ce0),
    .we0(u_a_11_we0),
    .d0(u_a_11_d0),
    .q0(u_a_11_q0)
);

heat2d_serial_hls_u_b_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
u_b_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_b_address0),
    .ce0(u_b_ce0),
    .we0(u_b_we0),
    .d0(u_b_d0),
    .q0(u_b_q0)
);

heat2d_serial_hls_u_b_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
u_b_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_b_1_address0),
    .ce0(u_b_1_ce0),
    .we0(u_b_1_we0),
    .d0(u_b_1_d0),
    .q0(u_b_1_q0)
);

heat2d_serial_hls_u_b_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
u_b_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_b_2_address0),
    .ce0(u_b_2_ce0),
    .we0(u_b_2_we0),
    .d0(u_b_2_d0),
    .q0(u_b_2_q0)
);

heat2d_serial_hls_u_b_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
u_b_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_b_3_address0),
    .ce0(u_b_3_ce0),
    .we0(u_b_3_we0),
    .d0(u_b_3_d0),
    .q0(u_b_3_q0)
);

heat2d_serial_hls_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_start),
    .ap_done(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_done),
    .ap_idle(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_idle),
    .ap_ready(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_ready),
    .u_in_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_in_address0),
    .u_in_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_in_ce0),
    .u_in_q0(u_in_q0),
    .u_a_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_address0),
    .u_a_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_ce0),
    .u_a_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_we0),
    .u_a_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_d0),
    .u_a_1_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_address0),
    .u_a_1_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_ce0),
    .u_a_1_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_we0),
    .u_a_1_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_d0),
    .u_a_2_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_address0),
    .u_a_2_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_ce0),
    .u_a_2_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_we0),
    .u_a_2_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_d0),
    .u_a_3_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_address0),
    .u_a_3_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_ce0),
    .u_a_3_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_we0),
    .u_a_3_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_d0),
    .u_a_4_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_address0),
    .u_a_4_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_ce0),
    .u_a_4_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_we0),
    .u_a_4_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_d0),
    .u_a_5_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_address0),
    .u_a_5_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_ce0),
    .u_a_5_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_we0),
    .u_a_5_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_d0),
    .u_a_6_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_address0),
    .u_a_6_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_ce0),
    .u_a_6_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_we0),
    .u_a_6_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_d0),
    .u_a_7_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_address0),
    .u_a_7_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_ce0),
    .u_a_7_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_we0),
    .u_a_7_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_d0),
    .u_a_8_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_address0),
    .u_a_8_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_ce0),
    .u_a_8_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_we0),
    .u_a_8_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_d0),
    .u_a_9_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_address0),
    .u_a_9_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_ce0),
    .u_a_9_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_we0),
    .u_a_9_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_d0),
    .u_a_10_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_address0),
    .u_a_10_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_ce0),
    .u_a_10_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_we0),
    .u_a_10_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_d0),
    .u_a_11_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_address0),
    .u_a_11_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_ce0),
    .u_a_11_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_we0),
    .u_a_11_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_d0),
    .u_b_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_address0),
    .u_b_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_ce0),
    .u_b_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_we0),
    .u_b_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_d0),
    .u_b_1_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_address0),
    .u_b_1_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_ce0),
    .u_b_1_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_we0),
    .u_b_1_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_d0),
    .u_b_2_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_address0),
    .u_b_2_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_ce0),
    .u_b_2_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_we0),
    .u_b_2_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_d0),
    .u_b_3_address0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_address0),
    .u_b_3_ce0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_ce0),
    .u_b_3_we0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_we0),
    .u_b_3_d0(grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_d0)
);

heat2d_serial_hls_heat2d_serial_hls_Pipeline_STORE_I_STORE_J grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_start),
    .ap_done(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_done),
    .ap_idle(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_idle),
    .ap_ready(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_ready),
    .u_out_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_address0),
    .u_out_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_ce0),
    .u_out_we0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_we0),
    .u_out_d0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_d0),
    .u_a_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_address0),
    .u_a_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_ce0),
    .u_a_q0(u_a_q0),
    .u_a_1_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_1_address0),
    .u_a_1_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_1_ce0),
    .u_a_1_q0(u_a_1_q0),
    .u_a_2_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_2_address0),
    .u_a_2_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_2_ce0),
    .u_a_2_q0(u_a_2_q0),
    .u_a_3_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_3_address0),
    .u_a_3_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_3_ce0),
    .u_a_3_q0(u_a_3_q0),
    .u_a_4_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_4_address0),
    .u_a_4_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_4_ce0),
    .u_a_4_q0(u_a_4_q0),
    .u_a_5_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_5_address0),
    .u_a_5_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_5_ce0),
    .u_a_5_q0(u_a_5_q0),
    .u_a_6_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_6_address0),
    .u_a_6_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_6_ce0),
    .u_a_6_q0(u_a_6_q0),
    .u_a_7_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_7_address0),
    .u_a_7_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_7_ce0),
    .u_a_7_q0(u_a_7_q0),
    .u_a_8_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_8_address0),
    .u_a_8_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_8_ce0),
    .u_a_8_q0(u_a_8_q0),
    .u_a_9_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_9_address0),
    .u_a_9_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_9_ce0),
    .u_a_9_q0(u_a_9_q0),
    .u_a_10_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_10_address0),
    .u_a_10_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_10_ce0),
    .u_a_10_q0(u_a_10_q0),
    .u_a_11_address0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_11_address0),
    .u_a_11_ce0(grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_11_ce0),
    .u_a_11_q0(u_a_11_q0)
);

heat2d_serial_hls_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_start),
    .ap_done(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_done),
    .ap_idle(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_idle),
    .ap_ready(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_ready),
    .u_a_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_address0),
    .u_a_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_ce0),
    .u_a_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_we0),
    .u_a_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_d0),
    .u_a_1_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_address0),
    .u_a_1_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_ce0),
    .u_a_1_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_we0),
    .u_a_1_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_d0),
    .u_a_2_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_address0),
    .u_a_2_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_ce0),
    .u_a_2_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_we0),
    .u_a_2_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_d0),
    .u_a_3_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_address0),
    .u_a_3_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_ce0),
    .u_a_3_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_we0),
    .u_a_3_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_d0),
    .u_a_4_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_address0),
    .u_a_4_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_ce0),
    .u_a_4_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_we0),
    .u_a_4_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_d0),
    .u_a_5_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_address0),
    .u_a_5_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_ce0),
    .u_a_5_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_we0),
    .u_a_5_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_d0),
    .u_a_6_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_address0),
    .u_a_6_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_ce0),
    .u_a_6_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_we0),
    .u_a_6_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_d0),
    .u_a_7_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_address0),
    .u_a_7_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_ce0),
    .u_a_7_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_we0),
    .u_a_7_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_d0),
    .u_a_8_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_address0),
    .u_a_8_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_ce0),
    .u_a_8_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_we0),
    .u_a_8_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_d0),
    .u_a_9_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_address0),
    .u_a_9_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_ce0),
    .u_a_9_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_we0),
    .u_a_9_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_d0),
    .u_a_10_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_address0),
    .u_a_10_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_ce0),
    .u_a_10_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_we0),
    .u_a_10_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_d0),
    .u_a_11_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_address0),
    .u_a_11_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_ce0),
    .u_a_11_we0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_we0),
    .u_a_11_d0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_d0),
    .u_b_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_address0),
    .u_b_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_ce0),
    .u_b_q0(u_b_q0),
    .u_b_1_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_1_address0),
    .u_b_1_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_1_ce0),
    .u_b_1_q0(u_b_1_q0),
    .u_b_2_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_2_address0),
    .u_b_2_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_2_ce0),
    .u_b_2_q0(u_b_2_q0),
    .u_b_3_address0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_3_address0),
    .u_b_3_ce0(grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_3_ce0),
    .u_b_3_q0(u_b_3_q0)
);

heat2d_serial_hls_heat2d_serial_hls_Pipeline_STENCIL_J grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_start),
    .ap_done(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_done),
    .ap_idle(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_idle),
    .ap_ready(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_ready),
    .mul_ln92(mul_ln92_reg_368),
    .u_a_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_address0),
    .u_a_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_ce0),
    .u_a_q0(u_a_q0),
    .mul_ln104(mul_ln104_reg_378),
    .mul_ln93(mul_ln93_reg_388),
    .u_a_1_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_1_address0),
    .u_a_1_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_1_ce0),
    .u_a_1_q0(u_a_1_q0),
    .u_a_2_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_2_address0),
    .u_a_2_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_2_ce0),
    .u_a_2_q0(u_a_2_q0),
    .u_a_3_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_3_address0),
    .u_a_3_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_3_ce0),
    .u_a_3_q0(u_a_3_q0),
    .u_a_4_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_4_address0),
    .u_a_4_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_4_ce0),
    .u_a_4_q0(u_a_4_q0),
    .u_a_5_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_5_address0),
    .u_a_5_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_5_ce0),
    .u_a_5_q0(u_a_5_q0),
    .u_a_6_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_6_address0),
    .u_a_6_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_6_ce0),
    .u_a_6_q0(u_a_6_q0),
    .u_a_7_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_7_address0),
    .u_a_7_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_7_ce0),
    .u_a_7_q0(u_a_7_q0),
    .u_a_8_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_8_address0),
    .u_a_8_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_8_ce0),
    .u_a_8_q0(u_a_8_q0),
    .u_a_9_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_9_address0),
    .u_a_9_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_9_ce0),
    .u_a_9_q0(u_a_9_q0),
    .u_a_10_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_10_address0),
    .u_a_10_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_10_ce0),
    .u_a_10_q0(u_a_10_q0),
    .u_a_11_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_11_address0),
    .u_a_11_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_11_ce0),
    .u_a_11_q0(u_a_11_q0),
    .i_1(i_reg_142),
    .u_b_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_address0),
    .u_b_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_ce0),
    .u_b_we0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_we0),
    .u_b_d0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_d0),
    .u_b_1_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_address0),
    .u_b_1_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_ce0),
    .u_b_1_we0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_we0),
    .u_b_1_d0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_d0),
    .u_b_2_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_address0),
    .u_b_2_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_ce0),
    .u_b_2_we0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_we0),
    .u_b_2_d0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_d0),
    .u_b_3_address0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_address0),
    .u_b_3_ce0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_ce0),
    .u_b_3_we0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_we0),
    .u_b_3_d0(grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_d0),
    .empty(trunc_ln92_reg_373)
);

heat2d_serial_hls_ctrl_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
ctrl_s_axi_U(
    .AWVALID(s_axi_ctrl_AWVALID),
    .AWREADY(s_axi_ctrl_AWREADY),
    .AWADDR(s_axi_ctrl_AWADDR),
    .WVALID(s_axi_ctrl_WVALID),
    .WREADY(s_axi_ctrl_WREADY),
    .WDATA(s_axi_ctrl_WDATA),
    .WSTRB(s_axi_ctrl_WSTRB),
    .ARVALID(s_axi_ctrl_ARVALID),
    .ARREADY(s_axi_ctrl_ARREADY),
    .ARADDR(s_axi_ctrl_ARADDR),
    .RVALID(s_axi_ctrl_RVALID),
    .RREADY(s_axi_ctrl_RREADY),
    .RDATA(s_axi_ctrl_RDATA),
    .RRESP(s_axi_ctrl_RRESP),
    .BVALID(s_axi_ctrl_BVALID),
    .BREADY(s_axi_ctrl_BREADY),
    .BRESP(s_axi_ctrl_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .num_steps(num_steps)
);

heat2d_serial_hls_urem_5ns_3ns_2_9_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_5ns_3ns_2_9_seq_1_U117(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_285_ap_start),
    .done(grp_fu_285_ap_done),
    .din0(i_reg_142),
    .din1(grp_fu_285_p1),
    .ce(1'b1),
    .dout(grp_fu_285_p2)
);

heat2d_serial_hls_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U118(
    .din0(mul_ln92_fu_299_p0),
    .din1(mul_ln92_fu_299_p1),
    .dout(mul_ln92_fu_299_p2)
);

heat2d_serial_hls_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U119(
    .din0(mul_ln104_fu_321_p0),
    .din1(mul_ln104_fu_321_p1),
    .dout(mul_ln104_fu_321_p2)
);

heat2d_serial_hls_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U120(
    .din0(mul_ln93_fu_338_p0),
    .din1(mul_ln93_fu_338_p1),
    .dout(mul_ln93_fu_338_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_ready == 1'b1)) begin
            grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_start_reg <= 1'b1;
        end else if ((grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_ready == 1'b1)) begin
            grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln84_fu_268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_start_reg <= 1'b1;
        end else if ((grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_ready == 1'b1)) begin
            grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln92_fu_279_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_start_reg <= 1'b1;
        end else if ((grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_ready == 1'b1)) begin
            grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        i_reg_142 <= add_ln104_reg_383;
    end else if (((icmp_ln84_fu_268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_142 <= 5'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        k_fu_68 <= 31'd0;
    end else if (((icmp_ln92_fu_279_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        k_fu_68 <= add_ln84_reg_360;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln104_reg_383 <= add_ln104_fu_328_p2;
        mul_ln104_reg_378 <= mul_ln104_fu_321_p2;
        mul_ln92_reg_368 <= mul_ln92_fu_299_p2;
        mul_ln93_reg_388 <= mul_ln93_fu_338_p2;
        trunc_ln92_reg_373 <= trunc_ln92_fu_306_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln84_reg_360 <= add_ln84_fu_273_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        num_steps_read_reg_352 <= num_steps;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln92_fu_279_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_285_ap_start = 1'b1;
    end else begin
        grp_fu_285_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_10_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_10_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_10_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_10_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_10_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_10_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_address0;
    end else begin
        u_a_10_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_10_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_10_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_10_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_10_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_10_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_10_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_ce0;
    end else begin
        u_a_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_10_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_10_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_d0;
    end else begin
        u_a_10_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_10_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_10_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_10_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_10_we0;
    end else begin
        u_a_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_11_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_11_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_11_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_11_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_11_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_11_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_address0;
    end else begin
        u_a_11_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_11_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_11_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_11_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_11_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_11_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_11_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_ce0;
    end else begin
        u_a_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_11_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_11_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_d0;
    end else begin
        u_a_11_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_11_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_11_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_11_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_11_we0;
    end else begin
        u_a_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_1_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_1_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_1_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_1_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_address0;
    end else begin
        u_a_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_1_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_1_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_1_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_1_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_ce0;
    end else begin
        u_a_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_1_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_1_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_d0;
    end else begin
        u_a_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_1_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_1_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_1_we0;
    end else begin
        u_a_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_2_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_2_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_2_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_2_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_address0;
    end else begin
        u_a_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_2_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_2_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_2_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_2_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_ce0;
    end else begin
        u_a_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_2_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_2_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_d0;
    end else begin
        u_a_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_2_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_2_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_2_we0;
    end else begin
        u_a_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_3_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_3_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_3_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_3_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_address0;
    end else begin
        u_a_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_3_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_3_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_3_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_3_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_ce0;
    end else begin
        u_a_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_3_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_3_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_d0;
    end else begin
        u_a_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_3_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_3_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_3_we0;
    end else begin
        u_a_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_4_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_4_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_4_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_4_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_address0;
    end else begin
        u_a_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_4_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_4_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_4_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_4_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_ce0;
    end else begin
        u_a_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_4_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_4_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_d0;
    end else begin
        u_a_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_4_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_4_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_4_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_4_we0;
    end else begin
        u_a_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_5_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_5_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_5_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_5_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_address0;
    end else begin
        u_a_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_5_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_5_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_5_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_5_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_ce0;
    end else begin
        u_a_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_5_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_5_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_d0;
    end else begin
        u_a_5_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_5_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_5_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_5_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_5_we0;
    end else begin
        u_a_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_6_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_6_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_6_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_6_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_address0;
    end else begin
        u_a_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_6_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_6_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_6_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_6_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_ce0;
    end else begin
        u_a_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_6_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_6_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_d0;
    end else begin
        u_a_6_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_6_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_6_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_6_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_6_we0;
    end else begin
        u_a_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_7_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_7_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_7_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_7_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_address0;
    end else begin
        u_a_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_7_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_7_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_7_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_7_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_ce0;
    end else begin
        u_a_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_7_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_7_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_d0;
    end else begin
        u_a_7_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_7_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_7_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_7_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_7_we0;
    end else begin
        u_a_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_8_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_8_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_8_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_8_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_8_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_8_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_address0;
    end else begin
        u_a_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_8_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_8_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_8_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_8_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_8_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_8_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_ce0;
    end else begin
        u_a_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_8_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_8_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_d0;
    end else begin
        u_a_8_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_8_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_8_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_8_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_8_we0;
    end else begin
        u_a_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_9_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_9_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_9_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_9_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_9_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_9_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_address0;
    end else begin
        u_a_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_9_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_9_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_9_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_9_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_9_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_9_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_ce0;
    end else begin
        u_a_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_9_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_9_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_d0;
    end else begin
        u_a_9_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_9_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_9_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_9_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_9_we0;
    end else begin
        u_a_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_address0;
    end else begin
        u_a_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_a_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_a_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_ce0;
    end else begin
        u_a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_d0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_d0;
    end else begin
        u_a_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        u_a_we0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_a_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_a_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_a_we0;
    end else begin
        u_a_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_1_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_b_1_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_1_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_address0;
    end else begin
        u_b_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_1_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_b_1_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_1_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_ce0;
    end else begin
        u_b_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_1_d0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_1_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_d0;
    end else begin
        u_b_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_1_we0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_1_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_1_we0;
    end else begin
        u_b_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_2_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_b_2_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_2_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_address0;
    end else begin
        u_b_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_2_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_b_2_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_2_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_ce0;
    end else begin
        u_b_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_2_d0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_2_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_d0;
    end else begin
        u_b_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_2_we0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_2_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_2_we0;
    end else begin
        u_b_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_3_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_b_3_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_3_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_address0;
    end else begin
        u_b_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_3_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_b_3_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_3_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_ce0;
    end else begin
        u_b_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_3_d0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_3_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_d0;
    end else begin
        u_b_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_3_we0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_3_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_3_we0;
    end else begin
        u_b_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_address0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_b_address0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_address0;
    end else begin
        u_b_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_ce0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        u_b_ce0 = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_u_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_ce0;
    end else begin
        u_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_d0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_d0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_d0;
    end else begin
        u_b_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        u_b_we0 = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_u_b_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_b_we0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_b_we0;
    end else begin
        u_b_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln84_fu_268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln92_fu_279_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln103_fu_311_p2 = ($signed(i_reg_142) + $signed(5'd31));

assign add_ln104_fu_328_p2 = (i_reg_142 + 5'd1);

assign add_ln84_fu_273_p2 = (k_fu_68 + 31'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_285_p1 = 5'd3;

assign grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_start = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_ap_start_reg;

assign grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_start = grp_heat2d_serial_hls_Pipeline_STENCIL_J_fu_230_ap_start_reg;

assign grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_start = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_ap_start_reg;

assign grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_start = grp_heat2d_serial_hls_Pipeline_SWAP_I_SWAP_J_fu_210_ap_start_reg;

assign icmp_ln84_fu_268_p2 = (($signed(zext_ln84_fu_264_p1) < $signed(num_steps_read_reg_352)) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_279_p2 = ((i_reg_142 == 5'd31) ? 1'b1 : 1'b0);

assign mul_ln104_fu_321_p0 = mul_ln104_fu_321_p00;

assign mul_ln104_fu_321_p00 = add_ln103_fu_311_p2;

assign mul_ln104_fu_321_p1 = 11'd43;

assign mul_ln92_fu_299_p0 = mul_ln92_fu_299_p00;

assign mul_ln92_fu_299_p00 = i_reg_142;

assign mul_ln92_fu_299_p1 = 11'd43;

assign mul_ln93_fu_338_p0 = mul_ln93_fu_338_p00;

assign mul_ln93_fu_338_p00 = add_ln104_fu_328_p2;

assign mul_ln93_fu_338_p1 = 11'd43;

assign trunc_ln92_fu_306_p1 = grp_fu_285_p2[1:0];

assign u_in_address0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_in_address0;

assign u_in_ce0 = grp_heat2d_serial_hls_Pipeline_LOAD_I_LOAD_J_fu_154_u_in_ce0;

assign u_out_address0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_address0;

assign u_out_ce0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_ce0;

assign u_out_d0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_d0;

assign u_out_we0 = grp_heat2d_serial_hls_Pipeline_STORE_I_STORE_J_fu_192_u_out_we0;

assign zext_ln84_fu_264_p1 = k_fu_68;

endmodule //heat2d_serial_hls
