// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module heat2d_serial_hls_heat2d_serial_hls_Pipeline_STORE_I_STORE_J (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        u_out_address0,
        u_out_ce0,
        u_out_we0,
        u_out_d0,
        u_a_address0,
        u_a_ce0,
        u_a_q0,
        u_a_1_address0,
        u_a_1_ce0,
        u_a_1_q0,
        u_a_2_address0,
        u_a_2_ce0,
        u_a_2_q0,
        u_a_3_address0,
        u_a_3_ce0,
        u_a_3_q0,
        u_a_4_address0,
        u_a_4_ce0,
        u_a_4_q0,
        u_a_5_address0,
        u_a_5_ce0,
        u_a_5_q0,
        u_a_6_address0,
        u_a_6_ce0,
        u_a_6_q0,
        u_a_7_address0,
        u_a_7_ce0,
        u_a_7_q0,
        u_a_8_address0,
        u_a_8_ce0,
        u_a_8_q0,
        u_a_9_address0,
        u_a_9_ce0,
        u_a_9_q0,
        u_a_10_address0,
        u_a_10_ce0,
        u_a_10_q0,
        u_a_11_address0,
        u_a_11_ce0,
        u_a_11_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] u_out_address0;
output   u_out_ce0;
output   u_out_we0;
output  [63:0] u_out_d0;
output  [6:0] u_a_address0;
output   u_a_ce0;
input  [63:0] u_a_q0;
output  [6:0] u_a_1_address0;
output   u_a_1_ce0;
input  [63:0] u_a_1_q0;
output  [6:0] u_a_2_address0;
output   u_a_2_ce0;
input  [63:0] u_a_2_q0;
output  [6:0] u_a_3_address0;
output   u_a_3_ce0;
input  [63:0] u_a_3_q0;
output  [6:0] u_a_4_address0;
output   u_a_4_ce0;
input  [63:0] u_a_4_q0;
output  [6:0] u_a_5_address0;
output   u_a_5_ce0;
input  [63:0] u_a_5_q0;
output  [6:0] u_a_6_address0;
output   u_a_6_ce0;
input  [63:0] u_a_6_q0;
output  [6:0] u_a_7_address0;
output   u_a_7_ce0;
input  [63:0] u_a_7_q0;
output  [6:0] u_a_8_address0;
output   u_a_8_ce0;
input  [63:0] u_a_8_q0;
output  [6:0] u_a_9_address0;
output   u_a_9_ce0;
input  [63:0] u_a_9_q0;
output  [6:0] u_a_10_address0;
output   u_a_10_ce0;
input  [63:0] u_a_10_q0;
output  [6:0] u_a_11_address0;
output   u_a_11_ce0;
input  [63:0] u_a_11_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln125_fu_297_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] select_ln125_1_fu_335_p3;
wire   [9:0] add_ln128_fu_375_p2;
reg   [9:0] add_ln128_reg_594;
reg   [9:0] add_ln128_reg_594_pp0_iter1_reg;
reg   [9:0] add_ln128_reg_594_pp0_iter2_reg;
reg   [9:0] add_ln128_reg_594_pp0_iter3_reg;
reg   [9:0] add_ln128_reg_594_pp0_iter4_reg;
reg   [9:0] add_ln128_reg_594_pp0_iter5_reg;
reg   [9:0] add_ln128_reg_594_pp0_iter6_reg;
reg   [9:0] add_ln128_reg_594_pp0_iter7_reg;
reg   [9:0] add_ln128_reg_594_pp0_iter8_reg;
wire   [1:0] trunc_ln126_fu_381_p1;
reg   [1:0] trunc_ln126_reg_599;
reg   [1:0] trunc_ln126_reg_599_pp0_iter1_reg;
reg   [1:0] trunc_ln126_reg_599_pp0_iter2_reg;
reg   [1:0] trunc_ln126_reg_599_pp0_iter3_reg;
reg   [1:0] trunc_ln126_reg_599_pp0_iter4_reg;
reg   [1:0] trunc_ln126_reg_599_pp0_iter5_reg;
reg   [1:0] trunc_ln126_reg_599_pp0_iter6_reg;
reg   [1:0] trunc_ln126_reg_599_pp0_iter7_reg;
reg   [1:0] trunc_ln126_reg_599_pp0_iter8_reg;
reg   [2:0] lshr_ln1_reg_604;
reg   [2:0] lshr_ln1_reg_604_pp0_iter1_reg;
reg   [2:0] lshr_ln1_reg_604_pp0_iter2_reg;
reg   [2:0] lshr_ln1_reg_604_pp0_iter3_reg;
reg   [2:0] lshr_ln1_reg_604_pp0_iter4_reg;
reg   [2:0] lshr_ln1_reg_604_pp0_iter5_reg;
reg   [2:0] lshr_ln1_reg_604_pp0_iter6_reg;
reg   [2:0] lshr_ln1_reg_604_pp0_iter7_reg;
reg   [3:0] tmp_33_cast_reg_609;
reg   [3:0] tmp_33_cast_reg_609_pp0_iter1_reg;
reg   [3:0] tmp_33_cast_reg_609_pp0_iter2_reg;
reg   [3:0] tmp_33_cast_reg_609_pp0_iter3_reg;
reg   [3:0] tmp_33_cast_reg_609_pp0_iter4_reg;
reg   [3:0] tmp_33_cast_reg_609_pp0_iter5_reg;
reg   [3:0] tmp_33_cast_reg_609_pp0_iter6_reg;
reg   [3:0] tmp_33_cast_reg_609_pp0_iter7_reg;
wire   [63:0] zext_ln128_1_fu_432_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln128_2_fu_452_p1;
reg   [5:0] j_fu_98;
wire   [5:0] add_ln126_fu_405_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_j_load;
reg   [5:0] i_fu_102;
reg   [5:0] ap_sig_allocacmp_i_load;
reg   [10:0] indvar_flatten13_fu_106;
wire   [10:0] add_ln125_1_fu_303_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten13_load;
reg    u_a_ce0_local;
reg    u_a_1_ce0_local;
reg    u_a_2_ce0_local;
reg    u_a_3_ce0_local;
reg    u_a_4_ce0_local;
reg    u_a_5_ce0_local;
reg    u_a_6_ce0_local;
reg    u_a_7_ce0_local;
reg    u_a_8_ce0_local;
reg    u_a_9_ce0_local;
reg    u_a_10_ce0_local;
reg    u_a_11_ce0_local;
reg    u_out_we0_local;
wire   [63:0] bitcast_ln128_fu_559_p1;
reg    u_out_ce0_local;
wire   [0:0] icmp_ln126_fu_321_p2;
wire   [5:0] add_ln125_fu_315_p2;
wire   [4:0] trunc_ln128_fu_343_p1;
wire   [5:0] mul_ln125_fu_359_p0;
wire   [7:0] mul_ln125_fu_359_p1;
wire   [2:0] grp_fu_365_p1;
wire   [5:0] select_ln125_fu_327_p3;
wire   [9:0] tmp_s_fu_347_p3;
wire   [9:0] zext_ln128_fu_371_p1;
wire   [12:0] mul_ln125_fu_359_p2;
wire   [6:0] tmp_3_fu_426_p3;
wire   [1:0] grp_fu_365_p2;
wire   [63:0] tmp_4_fu_456_p7;
wire   [1:0] trunc_ln125_fu_448_p1;
wire   [63:0] tmp_5_fu_476_p7;
wire   [63:0] tmp_6_fu_496_p7;
wire   [63:0] tmp_7_fu_516_p7;
wire   [63:0] tmp_4_fu_456_p9;
wire   [63:0] tmp_5_fu_476_p9;
wire   [63:0] tmp_6_fu_496_p9;
wire   [63:0] tmp_7_fu_516_p9;
wire   [63:0] tmp_8_fu_536_p9;
wire   [63:0] tmp_8_fu_536_p11;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [12:0] mul_ln125_fu_359_p00;
wire   [1:0] tmp_4_fu_456_p1;
wire   [1:0] tmp_4_fu_456_p3;
wire  signed [1:0] tmp_4_fu_456_p5;
wire   [1:0] tmp_5_fu_476_p1;
wire   [1:0] tmp_5_fu_476_p3;
wire  signed [1:0] tmp_5_fu_476_p5;
wire   [1:0] tmp_6_fu_496_p1;
wire   [1:0] tmp_6_fu_496_p3;
wire  signed [1:0] tmp_6_fu_496_p5;
wire   [1:0] tmp_7_fu_516_p1;
wire   [1:0] tmp_7_fu_516_p3;
wire  signed [1:0] tmp_7_fu_516_p5;
wire   [1:0] tmp_8_fu_536_p1;
wire   [1:0] tmp_8_fu_536_p3;
wire  signed [1:0] tmp_8_fu_536_p5;
wire  signed [1:0] tmp_8_fu_536_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 j_fu_98 = 6'd0;
#0 i_fu_102 = 6'd0;
#0 indvar_flatten13_fu_106 = 11'd0;
#0 ap_done_reg = 1'b0;
end

heat2d_serial_hls_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U97(
    .din0(mul_ln125_fu_359_p0),
    .din1(mul_ln125_fu_359_p1),
    .dout(mul_ln125_fu_359_p2)
);

heat2d_serial_hls_urem_6ns_3ns_2_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_6ns_3ns_2_10_1_U98(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln125_1_fu_335_p3),
    .din1(grp_fu_365_p1),
    .ce(1'b1),
    .dout(grp_fu_365_p2)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U99(
    .din0(u_a_q0),
    .din1(u_a_1_q0),
    .din2(u_a_2_q0),
    .def(tmp_4_fu_456_p7),
    .sel(trunc_ln125_fu_448_p1),
    .dout(tmp_4_fu_456_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U100(
    .din0(u_a_3_q0),
    .din1(u_a_4_q0),
    .din2(u_a_5_q0),
    .def(tmp_5_fu_476_p7),
    .sel(trunc_ln125_fu_448_p1),
    .dout(tmp_5_fu_476_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U101(
    .din0(u_a_6_q0),
    .din1(u_a_7_q0),
    .din2(u_a_8_q0),
    .def(tmp_6_fu_496_p7),
    .sel(trunc_ln125_fu_448_p1),
    .dout(tmp_6_fu_496_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U102(
    .din0(u_a_9_q0),
    .din1(u_a_10_q0),
    .din2(u_a_11_q0),
    .def(tmp_7_fu_516_p7),
    .sel(trunc_ln125_fu_448_p1),
    .dout(tmp_7_fu_516_p9)
);

(* dissolve_hierarchy = "yes" *) heat2d_serial_hls_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U103(
    .din0(tmp_4_fu_456_p9),
    .din1(tmp_5_fu_476_p9),
    .din2(tmp_6_fu_496_p9),
    .din3(tmp_7_fu_516_p9),
    .def(tmp_8_fu_536_p9),
    .sel(trunc_ln126_reg_599_pp0_iter8_reg),
    .dout(tmp_8_fu_536_p11)
);

heat2d_serial_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln125_fu_297_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_102 <= select_ln125_1_fu_335_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_102 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln125_fu_297_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_106 <= add_ln125_1_fu_303_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_106 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln125_fu_297_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_98 <= add_ln126_fu_405_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_98 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln128_reg_594 <= add_ln128_fu_375_p2;
        add_ln128_reg_594_pp0_iter1_reg <= add_ln128_reg_594;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        lshr_ln1_reg_604 <= {{select_ln125_fu_327_p3[4:2]}};
        lshr_ln1_reg_604_pp0_iter1_reg <= lshr_ln1_reg_604;
        tmp_33_cast_reg_609 <= {{mul_ln125_fu_359_p2[11:8]}};
        tmp_33_cast_reg_609_pp0_iter1_reg <= tmp_33_cast_reg_609;
        trunc_ln126_reg_599 <= trunc_ln126_fu_381_p1;
        trunc_ln126_reg_599_pp0_iter1_reg <= trunc_ln126_reg_599;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln128_reg_594_pp0_iter2_reg <= add_ln128_reg_594_pp0_iter1_reg;
        add_ln128_reg_594_pp0_iter3_reg <= add_ln128_reg_594_pp0_iter2_reg;
        add_ln128_reg_594_pp0_iter4_reg <= add_ln128_reg_594_pp0_iter3_reg;
        add_ln128_reg_594_pp0_iter5_reg <= add_ln128_reg_594_pp0_iter4_reg;
        add_ln128_reg_594_pp0_iter6_reg <= add_ln128_reg_594_pp0_iter5_reg;
        add_ln128_reg_594_pp0_iter7_reg <= add_ln128_reg_594_pp0_iter6_reg;
        add_ln128_reg_594_pp0_iter8_reg <= add_ln128_reg_594_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        lshr_ln1_reg_604_pp0_iter2_reg <= lshr_ln1_reg_604_pp0_iter1_reg;
        lshr_ln1_reg_604_pp0_iter3_reg <= lshr_ln1_reg_604_pp0_iter2_reg;
        lshr_ln1_reg_604_pp0_iter4_reg <= lshr_ln1_reg_604_pp0_iter3_reg;
        lshr_ln1_reg_604_pp0_iter5_reg <= lshr_ln1_reg_604_pp0_iter4_reg;
        lshr_ln1_reg_604_pp0_iter6_reg <= lshr_ln1_reg_604_pp0_iter5_reg;
        lshr_ln1_reg_604_pp0_iter7_reg <= lshr_ln1_reg_604_pp0_iter6_reg;
        tmp_33_cast_reg_609_pp0_iter2_reg <= tmp_33_cast_reg_609_pp0_iter1_reg;
        tmp_33_cast_reg_609_pp0_iter3_reg <= tmp_33_cast_reg_609_pp0_iter2_reg;
        tmp_33_cast_reg_609_pp0_iter4_reg <= tmp_33_cast_reg_609_pp0_iter3_reg;
        tmp_33_cast_reg_609_pp0_iter5_reg <= tmp_33_cast_reg_609_pp0_iter4_reg;
        tmp_33_cast_reg_609_pp0_iter6_reg <= tmp_33_cast_reg_609_pp0_iter5_reg;
        tmp_33_cast_reg_609_pp0_iter7_reg <= tmp_33_cast_reg_609_pp0_iter6_reg;
        trunc_ln126_reg_599_pp0_iter2_reg <= trunc_ln126_reg_599_pp0_iter1_reg;
        trunc_ln126_reg_599_pp0_iter3_reg <= trunc_ln126_reg_599_pp0_iter2_reg;
        trunc_ln126_reg_599_pp0_iter4_reg <= trunc_ln126_reg_599_pp0_iter3_reg;
        trunc_ln126_reg_599_pp0_iter5_reg <= trunc_ln126_reg_599_pp0_iter4_reg;
        trunc_ln126_reg_599_pp0_iter6_reg <= trunc_ln126_reg_599_pp0_iter5_reg;
        trunc_ln126_reg_599_pp0_iter7_reg <= trunc_ln126_reg_599_pp0_iter6_reg;
        trunc_ln126_reg_599_pp0_iter8_reg <= trunc_ln126_reg_599_pp0_iter7_reg;
    end
end

always @ (*) begin
    if (((icmp_ln125_fu_297_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 6'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 6'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_10_ce0_local = 1'b1;
    end else begin
        u_a_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_11_ce0_local = 1'b1;
    end else begin
        u_a_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_1_ce0_local = 1'b1;
    end else begin
        u_a_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_2_ce0_local = 1'b1;
    end else begin
        u_a_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_3_ce0_local = 1'b1;
    end else begin
        u_a_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_4_ce0_local = 1'b1;
    end else begin
        u_a_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_5_ce0_local = 1'b1;
    end else begin
        u_a_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_6_ce0_local = 1'b1;
    end else begin
        u_a_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_7_ce0_local = 1'b1;
    end else begin
        u_a_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_8_ce0_local = 1'b1;
    end else begin
        u_a_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_9_ce0_local = 1'b1;
    end else begin
        u_a_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        u_a_ce0_local = 1'b1;
    end else begin
        u_a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_out_ce0_local = 1'b1;
    end else begin
        u_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_out_we0_local = 1'b1;
    end else begin
        u_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln125_1_fu_303_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 11'd1);

assign add_ln125_fu_315_p2 = (ap_sig_allocacmp_i_load + 6'd1);

assign add_ln126_fu_405_p2 = (select_ln125_fu_327_p3 + 6'd1);

assign add_ln128_fu_375_p2 = (tmp_s_fu_347_p3 + zext_ln128_fu_371_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln128_fu_559_p1 = tmp_8_fu_536_p11;

assign grp_fu_365_p1 = 6'd3;

assign icmp_ln125_fu_297_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln126_fu_321_p2 = ((ap_sig_allocacmp_j_load == 6'd32) ? 1'b1 : 1'b0);

assign mul_ln125_fu_359_p0 = mul_ln125_fu_359_p00;

assign mul_ln125_fu_359_p00 = select_ln125_1_fu_335_p3;

assign mul_ln125_fu_359_p1 = 13'd86;

assign select_ln125_1_fu_335_p3 = ((icmp_ln126_fu_321_p2[0:0] == 1'b1) ? add_ln125_fu_315_p2 : ap_sig_allocacmp_i_load);

assign select_ln125_fu_327_p3 = ((icmp_ln126_fu_321_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_j_load);

assign tmp_3_fu_426_p3 = {{tmp_33_cast_reg_609_pp0_iter7_reg}, {lshr_ln1_reg_604_pp0_iter7_reg}};

assign tmp_4_fu_456_p7 = 'bx;

assign tmp_5_fu_476_p7 = 'bx;

assign tmp_6_fu_496_p7 = 'bx;

assign tmp_7_fu_516_p7 = 'bx;

assign tmp_8_fu_536_p9 = 'bx;

assign tmp_s_fu_347_p3 = {{trunc_ln128_fu_343_p1}, {5'd0}};

assign trunc_ln125_fu_448_p1 = grp_fu_365_p2[1:0];

assign trunc_ln126_fu_381_p1 = select_ln125_fu_327_p3[1:0];

assign trunc_ln128_fu_343_p1 = select_ln125_1_fu_335_p3[4:0];

assign u_a_10_address0 = zext_ln128_1_fu_432_p1;

assign u_a_10_ce0 = u_a_10_ce0_local;

assign u_a_11_address0 = zext_ln128_1_fu_432_p1;

assign u_a_11_ce0 = u_a_11_ce0_local;

assign u_a_1_address0 = zext_ln128_1_fu_432_p1;

assign u_a_1_ce0 = u_a_1_ce0_local;

assign u_a_2_address0 = zext_ln128_1_fu_432_p1;

assign u_a_2_ce0 = u_a_2_ce0_local;

assign u_a_3_address0 = zext_ln128_1_fu_432_p1;

assign u_a_3_ce0 = u_a_3_ce0_local;

assign u_a_4_address0 = zext_ln128_1_fu_432_p1;

assign u_a_4_ce0 = u_a_4_ce0_local;

assign u_a_5_address0 = zext_ln128_1_fu_432_p1;

assign u_a_5_ce0 = u_a_5_ce0_local;

assign u_a_6_address0 = zext_ln128_1_fu_432_p1;

assign u_a_6_ce0 = u_a_6_ce0_local;

assign u_a_7_address0 = zext_ln128_1_fu_432_p1;

assign u_a_7_ce0 = u_a_7_ce0_local;

assign u_a_8_address0 = zext_ln128_1_fu_432_p1;

assign u_a_8_ce0 = u_a_8_ce0_local;

assign u_a_9_address0 = zext_ln128_1_fu_432_p1;

assign u_a_9_ce0 = u_a_9_ce0_local;

assign u_a_address0 = zext_ln128_1_fu_432_p1;

assign u_a_ce0 = u_a_ce0_local;

assign u_out_address0 = zext_ln128_2_fu_452_p1;

assign u_out_ce0 = u_out_ce0_local;

assign u_out_d0 = bitcast_ln128_fu_559_p1;

assign u_out_we0 = u_out_we0_local;

assign zext_ln128_1_fu_432_p1 = tmp_3_fu_426_p3;

assign zext_ln128_2_fu_452_p1 = add_ln128_reg_594_pp0_iter8_reg;

assign zext_ln128_fu_371_p1 = select_ln125_fu_327_p3;

endmodule //heat2d_serial_hls_heat2d_serial_hls_Pipeline_STORE_I_STORE_J
