[hls]
relative_roots=/home/mallya/Desktop/LBP/solver
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=heat2d_serial_hls/LOAD_I  
syn.directive.array_partition=heat2d_serial_hls/u_a_0 dim=1 type=cyclic factor=3 variable=u_a_0
syn.directive.loop_flatten=heat2d_serial_hls/SWAP_I  
syn.directive.loop_flatten=heat2d_serial_hls/STORE_I  


